// Code generated by generator.go from ccgo_linux_s390x.go. DO NOT EDIT.

//go:build linux && s390x

package remind

import (
	"modernc.org/libc"
	"unsafe"
)

// resetGlobals assigns every package-level variable of the generated code
// its initial value, so that a run of the C main starts from the state of a
// fresh process.
func resetGlobals() {
	_NormalDrawing = Tline_drawing{
		Fgraphics_on:  __ccgo_ts,
		Fgraphics_off: __ccgo_ts,
		Ftlr:          __ccgo_ts + 1,
		Fbl:           __ccgo_ts + 1,
		Ftbl:          __ccgo_ts + 1,
		Fblr:          __ccgo_ts + 1,
		Ftblr:         __ccgo_ts + 1,
		Ftr:           __ccgo_ts + 1,
		Ftb:           __ccgo_ts + 3,
		Fbr:           __ccgo_ts + 1,
		Ftbr:          __ccgo_ts + 1,
		Ftl:           __ccgo_ts + 1,
		Flr:           __ccgo_ts + 5,
	}
	_VT100Drawing = Tline_drawing{
		Fgraphics_on:  __ccgo_ts + 7,
		Fgraphics_off: __ccgo_ts + 11,
		Ftlr:          __ccgo_ts + 15,
		Fbl:           __ccgo_ts + 17,
		Ftbl:          __ccgo_ts + 19,
		Fblr:          __ccgo_ts + 21,
		Ftblr:         __ccgo_ts + 23,
		Ftr:           __ccgo_ts + 25,
		Ftb:           __ccgo_ts + 27,
		Fbr:           __ccgo_ts + 29,
		Ftbr:          __ccgo_ts + 31,
		Ftl:           __ccgo_ts + 33,
		Flr:           __ccgo_ts + 35,
	}
	_encoding_is_utf8 = int32(0)
	_UTF8Drawing = Tline_drawing{
		Fgraphics_on:  __ccgo_ts,
		Fgraphics_off: __ccgo_ts,
		Ftlr:          __ccgo_ts + 37,
		Fbl:           __ccgo_ts + 41,
		Ftbl:          __ccgo_ts + 45,
		Fblr:          __ccgo_ts + 49,
		Ftblr:         __ccgo_ts + 53,
		Ftr:           __ccgo_ts + 57,
		Ftb:           __ccgo_ts + 61,
		Fbr:           __ccgo_ts + 65,
		Ftbr:          __ccgo_ts + 69,
		Ftl:           __ccgo_ts + 73,
		Flr:           __ccgo_ts + 77,
	}
	_VT100Colors = [2][2][2][2]uintptr{
		0: {
			0: {
				0: {
					0: __ccgo_ts + 81,
					1: __ccgo_ts + 89,
				},
				1: {
					0: __ccgo_ts + 97,
					1: __ccgo_ts + 105,
				},
			},
			1: {
				0: {
					0: __ccgo_ts + 113,
					1: __ccgo_ts + 121,
				},
				1: {
					0: __ccgo_ts + 129,
					1: __ccgo_ts + 137,
				},
			},
		},
		1: {
			0: {
				0: {
					0: __ccgo_ts + 145,
					1: __ccgo_ts + 153,
				},
				1: {
					0: __ccgo_ts + 161,
					1: __ccgo_ts + 169,
				},
			},
			1: {
				0: {
					0: __ccgo_ts + 177,
					1: __ccgo_ts + 185,
				},
				1: {
					0: __ccgo_ts + 193,
					1: __ccgo_ts + 201,
				},
			},
		},
	}
	_VT100BGColors = [2][2][2]uintptr{
		0: {
			0: {
				0: __ccgo_ts + 209,
				1: __ccgo_ts + 217,
			},
			1: {
				0: __ccgo_ts + 225,
				1: __ccgo_ts + 233,
			},
		},
		1: {
			0: {
				0: __ccgo_ts + 241,
				1: __ccgo_ts + 249,
			},
			1: {
				0: __ccgo_ts + 257,
				1: __ccgo_ts + 265,
			},
		},
	}
	_moonphase_emojis = [4]uintptr{
		0: __ccgo_ts + 273,
		1: __ccgo_ts + 278,
		2: __ccgo_ts + 283,
		3: __ccgo_ts + 288,
	}
	_moons = *new([32][32]uint8)
	_weeks = *new([32][32]uint8)
	_bgcolor = *new([32][3]int32)
	_linestruct = *new(uintptr)
	_XTerm256Colors = [256]Txterm256_colors{
		0: {},
		1: {
			Fr: int32(128),
		},
		2: {
			Fg: int32(128),
		},
		3: {
			Fr: int32(128),
			Fg: int32(128),
		},
		4: {
			Fb: int32(128),
		},
		5: {
			Fr: int32(128),
			Fb: int32(128),
		},
		6: {
			Fg: int32(128),
			Fb: int32(128),
		},
		7: {
			Fr: int32(192),
			Fg: int32(192),
			Fb: int32(192),
		},
		8: {
			Fr: int32(128),
			Fg: int32(128),
			Fb: int32(128),
		},
		9: {
			Fr: int32(255),
		},
		10: {
			Fg: int32(255),
		},
		11: {
			Fr: int32(255),
			Fg: int32(255),
		},
		12: {
			Fb: int32(255),
		},
		13: {
			Fr: int32(255),
			Fb: int32(255),
		},
		14: {
			Fg: int32(255),
			Fb: int32(255),
		},
		15: {
			Fr: int32(255),
			Fg: int32(255),
			Fb: int32(255),
		},
		16: {},
		17: {
			Fb: int32(95),
		},
		18: {
			Fb: int32(135),
		},
		19: {
			Fb: int32(175),
		},
		20: {
			Fb: int32(215),
		},
		21: {
			Fb: int32(255),
		},
		22: {
			Fg: int32(95),
		},
		23: {
			Fg: int32(95),
			Fb: int32(95),
		},
		24: {
			Fg: int32(95),
			Fb: int32(135),
		},
		25: {
			Fg: int32(95),
			Fb: int32(175),
		},
		26: {
			Fg: int32(95),
			Fb: int32(215),
		},
		27: {
			Fg: int32(95),
			Fb: int32(255),
		},
		28: {
			Fg: int32(135),
		},
		29: {
			Fg: int32(135),
			Fb: int32(95),
		},
		30: {
			Fg: int32(135),
			Fb: int32(135),
		},
		31: {
			Fg: int32(135),
			Fb: int32(175),
		},
		32: {
			Fg: int32(135),
			Fb: int32(215),
		},
		33: {
			Fg: int32(135),
			Fb: int32(255),
		},
		34: {
			Fg: int32(175),
		},
		35: {
			Fg: int32(175),
			Fb: int32(95),
		},
		36: {
			Fg: int32(175),
			Fb: int32(135),
		},
		37: {
			Fg: int32(175),
			Fb: int32(175),
		},
		38: {
			Fg: int32(175),
			Fb: int32(215),
		},
		39: {
			Fg: int32(175),
			Fb: int32(255),
		},
		40: {
			Fg: int32(215),
		},
		41: {
			Fg: int32(215),
			Fb: int32(95),
		},
		42: {
			Fg: int32(215),
			Fb: int32(135),
		},
		43: {
			Fg: int32(215),
			Fb: int32(175),
		},
		44: {
			Fg: int32(215),
			Fb: int32(215),
		},
		45: {
			Fg: int32(215),
			Fb: int32(255),
		},
		46: {
			Fg: int32(255),
		},
		47: {
			Fg: int32(255),
			Fb: int32(95),
		},
		48: {
			Fg: int32(255),
			Fb: int32(135),
		},
		49: {
			Fg: int32(255),
			Fb: int32(175),
		},
		50: {
			Fg: int32(255),
			Fb: int32(215),
		},
		51: {
			Fg: int32(255),
			Fb: int32(255),
		},
		52: {
			Fr: int32(95),
		},
		53: {
			Fr: int32(95),
			Fb: int32(95),
		},
		54: {
			Fr: int32(95),
			Fb: int32(135),
		},
		55: {
			Fr: int32(95),
			Fb: int32(175),
		},
		56: {
			Fr: int32(95),
			Fb: int32(215),
		},
		57: {
			Fr: int32(95),
			Fb: int32(255),
		},
		58: {
			Fr: int32(95),
			Fg: int32(95),
		},
		59: {
			Fr: int32(95),
			Fg: int32(95),
			Fb: int32(95),
		},
		60: {
			Fr: int32(95),
			Fg: int32(95),
			Fb: int32(135),
		},
		61: {
			Fr: int32(95),
			Fg: int32(95),
			Fb: int32(175),
		},
		62: {
			Fr: int32(95),
			Fg: int32(95),
			Fb: int32(215),
		},
		63: {
			Fr: int32(95),
			Fg: int32(95),
			Fb: int32(255),
		},
		64: {
			Fr: int32(95),
			Fg: int32(135),
		},
		65: {
			Fr: int32(95),
			Fg: int32(135),
			Fb: int32(95),
		},
		66: {
			Fr: int32(95),
			Fg: int32(135),
			Fb: int32(135),
		},
		67: {
			Fr: int32(95),
			Fg: int32(135),
			Fb: int32(175),
		},
		68: {
			Fr: int32(95),
			Fg: int32(135),
			Fb: int32(215),
		},
		69: {
			Fr: int32(95),
			Fg: int32(135),
			Fb: int32(255),
		},
		70: {
			Fr: int32(95),
			Fg: int32(175),
		},
		71: {
			Fr: int32(95),
			Fg: int32(175),
			Fb: int32(95),
		},
		72: {
			Fr: int32(95),
			Fg: int32(175),
			Fb: int32(135),
		},
		73: {
			Fr: int32(95),
			Fg: int32(175),
			Fb: int32(175),
		},
		74: {
			Fr: int32(95),
			Fg: int32(175),
			Fb: int32(215),
		},
		75: {
			Fr: int32(95),
			Fg: int32(175),
			Fb: int32(255),
		},
		76: {
			Fr: int32(95),
			Fg: int32(215),
		},
		77: {
			Fr: int32(95),
			Fg: int32(215),
			Fb: int32(95),
		},
		78: {
			Fr: int32(95),
			Fg: int32(215),
			Fb: int32(135),
		},
		79: {
			Fr: int32(95),
			Fg: int32(215),
			Fb: int32(175),
		},
		80: {
			Fr: int32(95),
			Fg: int32(215),
			Fb: int32(215),
		},
		81: {
			Fr: int32(95),
			Fg: int32(215),
			Fb: int32(255),
		},
		82: {
			Fr: int32(95),
			Fg: int32(255),
		},
		83: {
			Fr: int32(95),
			Fg: int32(255),
			Fb: int32(95),
		},
		84: {
			Fr: int32(95),
			Fg: int32(255),
			Fb: int32(135),
		},
		85: {
			Fr: int32(95),
			Fg: int32(255),
			Fb: int32(175),
		},
		86: {
			Fr: int32(95),
			Fg: int32(255),
			Fb: int32(215),
		},
		87: {
			Fr: int32(95),
			Fg: int32(255),
			Fb: int32(255),
		},
		88: {
			Fr: int32(135),
		},
		89: {
			Fr: int32(135),
			Fb: int32(95),
		},
		90: {
			Fr: int32(135),
			Fb: int32(135),
		},
		91: {
			Fr: int32(135),
			Fb: int32(175),
		},
		92: {
			Fr: int32(135),
			Fb: int32(215),
		},
		93: {
			Fr: int32(135),
			Fb: int32(255),
		},
		94: {
			Fr: int32(135),
			Fg: int32(95),
		},
		95: {
			Fr: int32(135),
			Fg: int32(95),
			Fb: int32(95),
		},
		96: {
			Fr: int32(135),
			Fg: int32(95),
			Fb: int32(135),
		},
		97: {
			Fr: int32(135),
			Fg: int32(95),
			Fb: int32(175),
		},
		98: {
			Fr: int32(135),
			Fg: int32(95),
			Fb: int32(215),
		},
		99: {
			Fr: int32(135),
			Fg: int32(95),
			Fb: int32(255),
		},
		100: {
			Fr: int32(135),
			Fg: int32(135),
		},
		101: {
			Fr: int32(135),
			Fg: int32(135),
			Fb: int32(95),
		},
		102: {
			Fr: int32(135),
			Fg: int32(135),
			Fb: int32(135),
		},
		103: {
			Fr: int32(135),
			Fg: int32(135),
			Fb: int32(175),
		},
		104: {
			Fr: int32(135),
			Fg: int32(135),
			Fb: int32(215),
		},
		105: {
			Fr: int32(135),
			Fg: int32(135),
			Fb: int32(255),
		},
		106: {
			Fr: int32(135),
			Fg: int32(175),
		},
		107: {
			Fr: int32(135),
			Fg: int32(175),
			Fb: int32(95),
		},
		108: {
			Fr: int32(135),
			Fg: int32(175),
			Fb: int32(135),
		},
		109: {
			Fr: int32(135),
			Fg: int32(175),
			Fb: int32(175),
		},
		110: {
			Fr: int32(135),
			Fg: int32(175),
			Fb: int32(215),
		},
		111: {
			Fr: int32(135),
			Fg: int32(175),
			Fb: int32(255),
		},
		112: {
			Fr: int32(135),
			Fg: int32(215),
		},
		113: {
			Fr: int32(135),
			Fg: int32(215),
			Fb: int32(95),
		},
		114: {
			Fr: int32(135),
			Fg: int32(215),
			Fb: int32(135),
		},
		115: {
			Fr: int32(135),
			Fg: int32(215),
			Fb: int32(175),
		},
		116: {
			Fr: int32(135),
			Fg: int32(215),
			Fb: int32(215),
		},
		117: {
			Fr: int32(135),
			Fg: int32(215),
			Fb: int32(255),
		},
		118: {
			Fr: int32(135),
			Fg: int32(255),
		},
		119: {
			Fr: int32(135),
			Fg: int32(255),
			Fb: int32(95),
		},
		120: {
			Fr: int32(135),
			Fg: int32(255),
			Fb: int32(135),
		},
		121: {
			Fr: int32(135),
			Fg: int32(255),
			Fb: int32(175),
		},
		122: {
			Fr: int32(135),
			Fg: int32(255),
			Fb: int32(215),
		},
		123: {
			Fr: int32(135),
			Fg: int32(255),
			Fb: int32(255),
		},
		124: {
			Fr: int32(175),
		},
		125: {
			Fr: int32(175),
			Fb: int32(95),
		},
		126: {
			Fr: int32(175),
			Fb: int32(135),
		},
		127: {
			Fr: int32(175),
			Fb: int32(175),
		},
		128: {
			Fr: int32(175),
			Fb: int32(215),
		},
		129: {
			Fr: int32(175),
			Fb: int32(255),
		},
		130: {
			Fr: int32(175),
			Fg: int32(95),
		},
		131: {
			Fr: int32(175),
			Fg: int32(95),
			Fb: int32(95),
		},
		132: {
			Fr: int32(175),
			Fg: int32(95),
			Fb: int32(135),
		},
		133: {
			Fr: int32(175),
			Fg: int32(95),
			Fb: int32(175),
		},
		134: {
			Fr: int32(175),
			Fg: int32(95),
			Fb: int32(215),
		},
		135: {
			Fr: int32(175),
			Fg: int32(95),
			Fb: int32(255),
		},
		136: {
			Fr: int32(175),
			Fg: int32(135),
		},
		137: {
			Fr: int32(175),
			Fg: int32(135),
			Fb: int32(95),
		},
		138: {
			Fr: int32(175),
			Fg: int32(135),
			Fb: int32(135),
		},
		139: {
			Fr: int32(175),
			Fg: int32(135),
			Fb: int32(175),
		},
		140: {
			Fr: int32(175),
			Fg: int32(135),
			Fb: int32(215),
		},
		141: {
			Fr: int32(175),
			Fg: int32(135),
			Fb: int32(255),
		},
		142: {
			Fr: int32(175),
			Fg: int32(175),
		},
		143: {
			Fr: int32(175),
			Fg: int32(175),
			Fb: int32(95),
		},
		144: {
			Fr: int32(175),
			Fg: int32(175),
			Fb: int32(135),
		},
		145: {
			Fr: int32(175),
			Fg: int32(175),
			Fb: int32(175),
		},
		146: {
			Fr: int32(175),
			Fg: int32(175),
			Fb: int32(215),
		},
		147: {
			Fr: int32(175),
			Fg: int32(175),
			Fb: int32(255),
		},
		148: {
			Fr: int32(175),
			Fg: int32(215),
		},
		149: {
			Fr: int32(175),
			Fg: int32(215),
			Fb: int32(95),
		},
		150: {
			Fr: int32(175),
			Fg: int32(215),
			Fb: int32(135),
		},
		151: {
			Fr: int32(175),
			Fg: int32(215),
			Fb: int32(175),
		},
		152: {
			Fr: int32(175),
			Fg: int32(215),
			Fb: int32(215),
		},
		153: {
			Fr: int32(175),
			Fg: int32(215),
			Fb: int32(255),
		},
		154: {
			Fr: int32(175),
			Fg: int32(255),
		},
		155: {
			Fr: int32(175),
			Fg: int32(255),
			Fb: int32(95),
		},
		156: {
			Fr: int32(175),
			Fg: int32(255),
			Fb: int32(135),
		},
		157: {
			Fr: int32(175),
			Fg: int32(255),
			Fb: int32(175),
		},
		158: {
			Fr: int32(175),
			Fg: int32(255),
			Fb: int32(215),
		},
		159: {
			Fr: int32(175),
			Fg: int32(255),
			Fb: int32(255),
		},
		160: {
			Fr: int32(215),
		},
		161: {
			Fr: int32(215),
			Fb: int32(95),
		},
		162: {
			Fr: int32(215),
			Fb: int32(135),
		},
		163: {
			Fr: int32(215),
			Fb: int32(175),
		},
		164: {
			Fr: int32(215),
			Fb: int32(215),
		},
		165: {
			Fr: int32(215),
			Fb: int32(255),
		},
		166: {
			Fr: int32(215),
			Fg: int32(95),
		},
		167: {
			Fr: int32(215),
			Fg: int32(95),
			Fb: int32(95),
		},
		168: {
			Fr: int32(215),
			Fg: int32(95),
			Fb: int32(135),
		},
		169: {
			Fr: int32(215),
			Fg: int32(95),
			Fb: int32(175),
		},
		170: {
			Fr: int32(215),
			Fg: int32(95),
			Fb: int32(215),
		},
		171: {
			Fr: int32(215),
			Fg: int32(95),
			Fb: int32(255),
		},
		172: {
			Fr: int32(215),
			Fg: int32(135),
		},
		173: {
			Fr: int32(215),
			Fg: int32(135),
			Fb: int32(95),
		},
		174: {
			Fr: int32(215),
			Fg: int32(135),
			Fb: int32(135),
		},
		175: {
			Fr: int32(215),
			Fg: int32(135),
			Fb: int32(175),
		},
		176: {
			Fr: int32(215),
			Fg: int32(135),
			Fb: int32(215),
		},
		177: {
			Fr: int32(215),
			Fg: int32(135),
			Fb: int32(255),
		},
		178: {
			Fr: int32(215),
			Fg: int32(175),
		},
		179: {
			Fr: int32(215),
			Fg: int32(175),
			Fb: int32(95),
		},
		180: {
			Fr: int32(215),
			Fg: int32(175),
			Fb: int32(135),
		},
		181: {
			Fr: int32(215),
			Fg: int32(175),
			Fb: int32(175),
		},
		182: {
			Fr: int32(215),
			Fg: int32(175),
			Fb: int32(215),
		},
		183: {
			Fr: int32(215),
			Fg: int32(175),
			Fb: int32(255),
		},
		184: {
			Fr: int32(215),
			Fg: int32(215),
		},
		185: {
			Fr: int32(215),
			Fg: int32(215),
			Fb: int32(95),
		},
		186: {
			Fr: int32(215),
			Fg: int32(215),
			Fb: int32(135),
		},
		187: {
			Fr: int32(215),
			Fg: int32(215),
			Fb: int32(175),
		},
		188: {
			Fr: int32(215),
			Fg: int32(215),
			Fb: int32(215),
		},
		189: {
			Fr: int32(215),
			Fg: int32(215),
			Fb: int32(255),
		},
		190: {
			Fr: int32(215),
			Fg: int32(255),
		},
		191: {
			Fr: int32(215),
			Fg: int32(255),
			Fb: int32(95),
		},
		192: {
			Fr: int32(215),
			Fg: int32(255),
			Fb: int32(135),
		},
		193: {
			Fr: int32(215),
			Fg: int32(255),
			Fb: int32(175),
		},
		194: {
			Fr: int32(215),
			Fg: int32(255),
			Fb: int32(215),
		},
		195: {
			Fr: int32(215),
			Fg: int32(255),
			Fb: int32(255),
		},
		196: {
			Fr: int32(255),
		},
		197: {
			Fr: int32(255),
			Fb: int32(95),
		},
		198: {
			Fr: int32(255),
			Fb: int32(135),
		},
		199: {
			Fr: int32(255),
			Fb: int32(175),
		},
		200: {
			Fr: int32(255),
			Fb: int32(215),
		},
		201: {
			Fr: int32(255),
			Fb: int32(255),
		},
		202: {
			Fr: int32(255),
			Fg: int32(95),
		},
		203: {
			Fr: int32(255),
			Fg: int32(95),
			Fb: int32(95),
		},
		204: {
			Fr: int32(255),
			Fg: int32(95),
			Fb: int32(135),
		},
		205: {
			Fr: int32(255),
			Fg: int32(95),
			Fb: int32(175),
		},
		206: {
			Fr: int32(255),
			Fg: int32(95),
			Fb: int32(215),
		},
		207: {
			Fr: int32(255),
			Fg: int32(95),
			Fb: int32(255),
		},
		208: {
			Fr: int32(255),
			Fg: int32(135),
		},
		209: {
			Fr: int32(255),
			Fg: int32(135),
			Fb: int32(95),
		},
		210: {
			Fr: int32(255),
			Fg: int32(135),
			Fb: int32(135),
		},
		211: {
			Fr: int32(255),
			Fg: int32(135),
			Fb: int32(175),
		},
		212: {
			Fr: int32(255),
			Fg: int32(135),
			Fb: int32(215),
		},
		213: {
			Fr: int32(255),
			Fg: int32(135),
			Fb: int32(255),
		},
		214: {
			Fr: int32(255),
			Fg: int32(175),
		},
		215: {
			Fr: int32(255),
			Fg: int32(175),
			Fb: int32(95),
		},
		216: {
			Fr: int32(255),
			Fg: int32(175),
			Fb: int32(135),
		},
		217: {
			Fr: int32(255),
			Fg: int32(175),
			Fb: int32(175),
		},
		218: {
			Fr: int32(255),
			Fg: int32(175),
			Fb: int32(215),
		},
		219: {
			Fr: int32(255),
			Fg: int32(175),
			Fb: int32(255),
		},
		220: {
			Fr: int32(255),
			Fg: int32(215),
		},
		221: {
			Fr: int32(255),
			Fg: int32(215),
			Fb: int32(95),
		},
		222: {
			Fr: int32(255),
			Fg: int32(215),
			Fb: int32(135),
		},
		223: {
			Fr: int32(255),
			Fg: int32(215),
			Fb: int32(175),
		},
		224: {
			Fr: int32(255),
			Fg: int32(215),
			Fb: int32(215),
		},
		225: {
			Fr: int32(255),
			Fg: int32(215),
			Fb: int32(255),
		},
		226: {
			Fr: int32(255),
			Fg: int32(255),
		},
		227: {
			Fr: int32(255),
			Fg: int32(255),
			Fb: int32(95),
		},
		228: {
			Fr: int32(255),
			Fg: int32(255),
			Fb: int32(135),
		},
		229: {
			Fr: int32(255),
			Fg: int32(255),
			Fb: int32(175),
		},
		230: {
			Fr: int32(255),
			Fg: int32(255),
			Fb: int32(215),
		},
		231: {
			Fr: int32(255),
			Fg: int32(255),
			Fb: int32(255),
		},
		232: {
			Fr: int32(8),
			Fg: int32(8),
			Fb: int32(8),
		},
		233: {
			Fr: int32(18),
			Fg: int32(18),
			Fb: int32(18),
		},
		234: {
			Fr: int32(28),
			Fg: int32(28),
			Fb: int32(28),
		},
		235: {
			Fr: int32(38),
			Fg: int32(38),
			Fb: int32(38),
		},
		236: {
			Fr: int32(48),
			Fg: int32(48),
			Fb: int32(48),
		},
		237: {
			Fr: int32(58),
			Fg: int32(58),
			Fb: int32(58),
		},
		238: {
			Fr: int32(68),
			Fg: int32(68),
			Fb: int32(68),
		},
		239: {
			Fr: int32(78),
			Fg: int32(78),
			Fb: int32(78),
		},
		240: {
			Fr: int32(88),
			Fg: int32(88),
			Fb: int32(88),
		},
		241: {
			Fr: int32(98),
			Fg: int32(98),
			Fb: int32(98),
		},
		242: {
			Fr: int32(108),
			Fg: int32(108),
			Fb: int32(108),
		},
		243: {
			Fr: int32(118),
			Fg: int32(118),
			Fb: int32(118),
		},
		244: {
			Fr: int32(128),
			Fg: int32(128),
			Fb: int32(128),
		},
		245: {
			Fr: int32(138),
			Fg: int32(138),
			Fb: int32(138),
		},
		246: {
			Fr: int32(148),
			Fg: int32(148),
			Fb: int32(148),
		},
		247: {
			Fr: int32(158),
			Fg: int32(158),
			Fb: int32(158),
		},
		248: {
			Fr: int32(168),
			Fg: int32(168),
			Fb: int32(168),
		},
		249: {
			Fr: int32(178),
			Fg: int32(178),
			Fb: int32(178),
		},
		250: {
			Fr: int32(188),
			Fg: int32(188),
			Fb: int32(188),
		},
		251: {
			Fr: int32(198),
			Fg: int32(198),
			Fb: int32(198),
		},
		252: {
			Fr: int32(208),
			Fg: int32(208),
			Fb: int32(208),
		},
		253: {
			Fr: int32(218),
			Fg: int32(218),
			Fb: int32(218),
		},
		254: {
			Fr: int32(228),
			Fg: int32(228),
			Fb: int32(228),
		},
		255: {
			Fr: int32(238),
			Fg: int32(238),
			Fb: int32(238),
		},
	}
	_CalColumn = *new([7]uintptr)
	_ColToDay = *new([7]int32)
	_ColSpaces = *new(int32)
	_DidAMonth = *new(int32)
	_DidAWeek = *new(int32)
	_DidADay = *new(int32)
	_buf = *new([256]uint8)
	_buf1 = *new([80]uint8)
	_buf2 = *new([40]uint8)
	_buf3 = *new([40]uint8)
	_buf4 = *new([128]uint8)
	_buf5 = *new([128]uint8)
	_out = *new([128]uint8)
	_DedupeTable = *new(Thash_table)
	_NumMallocs = uint64(0)
	_BytesMalloced = uint64(0)
	_CalledEnterTimezone = int32(0)
	_func = *new([32]uint8)
	_expr_node_free_list = libc.UintptrFromInt32(0)
	_parse_level_high_water = int32(0)
	_ExprNodesAllocated = int32(0)
	_ExprNodesHighWater = int32(0)
	_ExprNodesUsed = int32(0)
	_CurrentUserFunc = libc.UintptrFromInt32(0)
	_wbuf = *new([41]Twchar_t)
	_cbuf = *new([321]uint8)
	_printbuf = TDynamicBuffer{
		FstaticBuf: [32]uint8{},
	}
	_join = libc.UintptrFromInt32(0)
	_FilenameHashTable = *new(Thash_table)
	_CachedFiles = libc.UintptrFromInt32(0)
	_CLine = libc.UintptrFromInt32(0)
	_CachedDirectoryChains = libc.UintptrFromInt32(0)
	_FileName = libc.UintptrFromInt32(0)
	_fp = *new(uintptr)
	_IStack = *new([9]TIncludeStruct)
	_IStackPtr = int32(0)
	_LastCatchError = int32(m_OK)
	_CacheDse = -int32(1)
	_CacheYear = *new(int32)
	_CacheMon = *new(int32)
	_CacheDay = *new(int32)
	_CacheHebDse = -int32(1)
	_CacheHebYear = *new(int32)
	_CacheHebMon = *new(int32)
	_CacheHebDay = *new(int32)
	_in_ford = *new(int32)
	_psshade_warned = int32(0)
	_psmoon_warned = int32(0)
	_LastTrig = int32(0)
	_bucket_choices = [28]Tsize_t{
		0:  uint64(7),
		1:  uint64(17),
		2:  uint64(37),
		3:  uint64(79),
		4:  uint64(163),
		5:  uint64(331),
		6:  uint64(673),
		7:  uint64(1361),
		8:  uint64(2729),
		9:  uint64(5471),
		10: uint64(10949),
		11: uint64(21911),
		12: uint64(43853),
		13: uint64(87719),
		14: uint64(175447),
		15: uint64(350899),
		16: uint64(701819),
		17: uint64(1403641),
		18: uint64(2807303),
		19: uint64(5614657),
		20: uint64(11229331),
		21: uint64(22458671),
		22: uint64(44917381),
		23: uint64(89834777),
		24: uint64(179669557),
		25: uint64(359339171),
		26: uint64(718678369),
		27: uint64(1437356741),
	}
	_HebMonthNames = [14]uintptr{
		0:  __ccgo_ts + 12616,
		1:  __ccgo_ts + 12624,
		2:  __ccgo_ts + 12632,
		3:  __ccgo_ts + 12639,
		4:  __ccgo_ts + 12645,
		5:  __ccgo_ts + 12651,
		6:  __ccgo_ts + 12658,
		7:  __ccgo_ts + 12665,
		8:  __ccgo_ts + 12671,
		9:  __ccgo_ts + 12676,
		10: __ccgo_ts + 12682,
		11: __ccgo_ts + 12688,
		12: __ccgo_ts + 12691,
		13: __ccgo_ts + 12696,
	}
	_IvritMonthNames = [14]uintptr{
		0:  __ccgo_ts + 12701,
		1:  __ccgo_ts + 12710,
		2:  __ccgo_ts + 12721,
		3:  __ccgo_ts + 12730,
		4:  __ccgo_ts + 12737,
		5:  __ccgo_ts + 12744,
		6:  __ccgo_ts + 12755,
		7:  __ccgo_ts + 12766,
		8:  __ccgo_ts + 12775,
		9:  __ccgo_ts + 12784,
		10: __ccgo_ts + 12793,
		11: __ccgo_ts + 12802,
		12: __ccgo_ts + 12807,
		13: __ccgo_ts + 12816,
	}
	_AltMonthSpellings = [17]TAltMonthName{
		0: {
			Fname: __ccgo_ts + 12823,
		},
		1: {
			Fname: __ccgo_ts + 12830,
		},
		2: {
			Fname: __ccgo_ts + 12838,
			Fmon:  int32(m_HESHVAN),
		},
		3: {
			Fname: __ccgo_ts + 12847,
			Fmon:  int32(m_HESHVAN),
		},
		4: {
			Fname: __ccgo_ts + 12856,
			Fmon:  int32(m_SHVAT),
		},
		5: {
			Fname: __ccgo_ts + 12863,
			Fmon:  int32(m_TAMUZ),
		},
		6: {
			Fname: __ccgo_ts + 12870,
			Fmon:  int32(m_ADARA),
		},
		7: {
			Fname: __ccgo_ts + 12877,
			Fmon:  int32(m_ADARA),
		},
		8: {
			Fname: __ccgo_ts + 12884,
			Fmon:  int32(m_ADARA),
		},
		9: {
			Fname: __ccgo_ts + 12894,
			Fmon:  int32(m_ADARA),
		},
		10: {
			Fname: __ccgo_ts + 12903,
			Fmon:  int32(m_ADARA),
		},
		11: {
			Fname: __ccgo_ts + 12912,
			Fmon:  int32(m_ADARB),
		},
		12: {
			Fname: __ccgo_ts + 12919,
			Fmon:  int32(m_ADARB),
		},
		13: {
			Fname: __ccgo_ts + 12927,
			Fmon:  int32(m_ADARB),
		},
		14: {
			Fname: __ccgo_ts + 12937,
			Fmon:  int32(m_ADARB),
		},
		15: {
			Fname: __ccgo_ts + 12946,
			Fmon:  int32(m_ADARB),
		},
		16: {
			Fname: __ccgo_ts + 12956,
			Fmon:  int32(m_IYAR),
		},
	}
	_MaxMonLen = [14]uint8{
		0:  uint8(30),
		1:  uint8(30),
		2:  uint8(30),
		3:  uint8(29),
		4:  uint8(30),
		5:  uint8(30),
		6:  uint8(29),
		7:  uint8(30),
		8:  uint8(29),
		9:  uint8(30),
		10: uint8(29),
		11: uint8(30),
		12: uint8(29),
		13: uint8(29),
	}
	_HebIsLeap = [19]uint8{
		2:  uint8(1),
		5:  uint8(1),
		7:  uint8(1),
		10: uint8(1),
		13: uint8(1),
		16: uint8(1),
		18: uint8(1),
	}
	_monlen = [14]uint8{
		0:  uint8(30),
		1:  uint8(29),
		2:  uint8(30),
		3:  uint8(29),
		4:  uint8(30),
		6:  uint8(29),
		7:  uint8(30),
		8:  uint8(29),
		9:  uint8(30),
		10: uint8(29),
		11: uint8(30),
		12: uint8(29),
		13: uint8(29),
	}
	_if_pointer = int32(0)
	_base_pointer = int32(0)
	_return_encountered = int32(0)
	_IfArray = *new([64]Tifentry)
	_should_guess_terminal_background = int32(1)
	_BadDate = __ccgo_ts + 13177
	_default_filename_buf = *new(TDynamicBuffer)
	_home = *new(uintptr)
	_shell = *new(uintptr)
	_username = *new(uintptr)
	_logname = *new(uintptr)
	_orig_termios = *new(Ttermios)
	_got_sigint = int32(0)
	_warned_about_mixed_case = int32(0)
	_buf6 = *new([64]uint8)
	_FullOmitArray = *new([1000]int32)
	_PartialOmitArray = *new([366]int32)
	_SavedOmitContexts = libc.UintptrFromInt32(0)
	_QueueHead = libc.UintptrFromInt32(0)
	_FileModTime = *new(Ttime_t)
	_StatBuf = *new(Tstat)
	_got_sighup = int32(0)
	_SortedQueue = libc.UintptrFromInt32(0)
	_UserFuncStack = libc.UintptrFromInt32(0)
	_DontEscapeMe = [71]uint8{'1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '_', '-', '=', '+', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '@', '.', ',', '/'}
	_HaveZoneinfoDir = -int32(1)
	_callstack = libc.UintptrFromInt32(0)
	_freecs = libc.UintptrFromInt32(0)
	_buf7 = *new([128]uint8)
	_VHashTbl = *new(Thash_table)
	_Ucached = -int32(1)
	_Udcached = -int32(1)
	_Umcached = -int32(1)
	_Uycached = -int32(1)
	_SysVarArr = [127]TSysVar{
		0: {
			Fname:       __ccgo_ts + 22774,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XAddBlankLines)),
			Fmax:        int32(1),
		},
		1: {
			Fname:       __ccgo_ts + 22788,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4171,
		},
		2: {
			Fname:       __ccgo_ts + 22792,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 1805,
		},
		3: {
			Fname:       __ccgo_ts + 22795,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 5002,
		},
		4: {
			Fname:       __ccgo_ts + 12371,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12371,
		},
		5: {
			Fname:       __ccgo_ts + 22799,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 5089,
		},
		6: {
			Fname:       __ccgo_ts + 12391,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12391,
		},
		7: {
			Fname:       __ccgo_ts + 22802,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XCalculateUTC)),
			Fmax:        int32(1),
		},
		8: {
			Fname:  __ccgo_ts + 22810,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDoCalendar)),
		},
		9: {
			Fname:  __ccgo_ts + 22818,
			Ftype1: int32(m_STR_TYPE10),
			Fvalue: uintptr(unsafe.Pointer(&XCalType)),
		},
		10: {
			Fname:  __ccgo_ts + 22826,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDaemon)),
		},
		11: {
			Fname:       __ccgo_ts + 22833,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		12: {
			Fname:       __ccgo_ts + 22841,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		13: {
			Fname:       __ccgo_ts + 12425,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12425,
		},
		14: {
			Fname:       __ccgo_ts + 22853,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XDedupeReminders)),
			Fmax:        int32(1),
		},
		15: {
			Fname:       __ccgo_ts + 22869,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		16: {
			Fname:       __ccgo_ts + 22882,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		17: {
			Fname:       __ccgo_ts + 22896,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XDefaultDelta)),
			Fmax:        int32(10000),
		},
		18: {
			Fname:       __ccgo_ts + 22909,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XDefaultPrio)),
			Fmax:        int32(9999),
		},
		19: {
			Fname:       __ccgo_ts + 22921,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XDefaultTDelta)),
			Fmax:        int32(m_MINUTES_PER_DAY),
		},
		20: {
			Fname:  __ccgo_ts + 22935,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDeltaOverride)),
		},
		21: {
			Fname:  __ccgo_ts + 22949,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDontFork)),
		},
		22: {
			Fname:  __ccgo_ts + 22958,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDontQueue)),
		},
		23: {
			Fname:  __ccgo_ts + 22968,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDontIssueAts)),
		},
		24: {
			Fname:       __ccgo_ts + 22980,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_STR_TYPE10),
			Fvalue:      uintptr(unsafe.Pointer(&XEndSent)),
		},
		25: {
			Fname:       __ccgo_ts + 22988,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_STR_TYPE10),
			Fvalue:      uintptr(unsafe.Pointer(&XEndSentIg)),
		},
		26: {
			Fname:       __ccgo_ts + 22998,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		27: {
			Fname:       __ccgo_ts + 12356,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12356,
		},
		28: {
			Fname:       __ccgo_ts + 23018,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XFirstIndent)),
			Fmax:        int32(132),
		},
		29: {
			Fname:       __ccgo_ts + 23030,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XFoldYear)),
			Fmax:        int32(1),
		},
		30: {
			Fname:       __ccgo_ts + 23039,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XFormWidth)),
			Fmin:        int32(20),
			Fmax:        int32(500),
		},
		31: {
			Fname:       __ccgo_ts + 9174,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9174,
		},
		32: {
			Fname:       __ccgo_ts + 23049,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4175,
		},
		33: {
			Fname:  __ccgo_ts + 23057,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XHideCompletedTodos)),
		},
		34: {
			Fname:       __ccgo_ts + 23076,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4975,
		},
		35: {
			Fname:       __ccgo_ts + 23081,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_STR_TYPE10),
			Fvalue:      uintptr(unsafe.Pointer(&XDynamicHplu)),
		},
		36: {
			Fname:  __ccgo_ts + 23086,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XHush)),
		},
		37: {
			Fname:  __ccgo_ts + 23095,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XIgnoreOnce)),
		},
		38: {
			Fname:  __ccgo_ts + 23106,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XInfiniteDelta)),
		},
		39: {
			Fname:  __ccgo_ts + 23115,
			Ftype1: int32(m_CONST_INT_TYPE3),
			Fmin:   int32(m_INT_MAX10),
		},
		40: {
			Fname:  __ccgo_ts + 23122,
			Ftype1: int32(m_CONST_INT_TYPE3),
			Fmin:   -libc.Int32FromInt32(1) - libc.Int32FromInt32(0x7fffffff),
		},
		41: {
			Fname:       __ccgo_ts + 23129,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 5092,
		},
		42: {
			Fname:       __ccgo_ts + 12348,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12348,
		},
		43: {
			Fname:  __ccgo_ts + 23132,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XJSONMode)),
		},
		44: {
			Fname:       __ccgo_ts + 12386,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12386,
		},
		45: {
			Fname:       __ccgo_ts + 12381,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12381,
		},
		46: {
			Fname:       __ccgo_ts + 23141,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		47: {
			Fname:       __ccgo_ts + 23148,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		48: {
			Fname:       __ccgo_ts + 23157,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		49: {
			Fname:       __ccgo_ts + 23164,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		50: {
			Fname:       __ccgo_ts + 23171,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_STR_TYPE10),
			Fvalue:      uintptr(unsafe.Pointer(&XLocation)),
		},
		51: {
			Fname:       __ccgo_ts + 23180,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		52: {
			Fname:       __ccgo_ts + 23188,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		53: {
			Fname:       __ccgo_ts + 23198,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		54: {
			Fname:       __ccgo_ts + 23206,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		55: {
			Fname:       __ccgo_ts + 12365,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12365,
		},
		56: {
			Fname:       __ccgo_ts + 23214,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMaxCachedLines)),
			Fmax:        int32(m_INT_MAX10),
		},
		57: {
			Fname:  __ccgo_ts + 23229,
			Ftype1: int32(m_CONST_INT_TYPE3),
			Fmin:   int32(m_MAX_FULL_OMITS),
		},
		58: {
			Fname:       __ccgo_ts + 23242,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMaxIncludeCmdLines)),
			Fmax:        int32(m_INT_MAX10),
		},
		59: {
			Fname:       __ccgo_ts + 23261,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMaxLateMinutes)),
			Fmax:        int32(m_MINUTES_PER_DAY),
		},
		60: {
			Fname:       __ccgo_ts + 23276,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMaxLineLength)),
			Fmax:        int32(m_INT_MAX10),
		},
		61: {
			Fname:  __ccgo_ts + 23290,
			Ftype1: int32(m_CONST_INT_TYPE3),
			Fmin:   int32(m_MAX_PARTIAL_OMITS),
		},
		62: {
			Fname:       __ccgo_ts + 23306,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMaxSatIter)),
			Fmin:        int32(10),
			Fmax:        int32(m_INT_MAX10),
		},
		63: {
			Fname:       __ccgo_ts + 23317,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMaxStringLen)),
			Fmin:        -int32(1),
			Fmax:        int32(m_INT_MAX10),
		},
		64: {
			Fname:       __ccgo_ts + 12377,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12377,
		},
		65: {
			Fname:       __ccgo_ts + 23330,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XMinsFromUTC)),
			Fmin:        -int32(780),
			Fmax:        int32(780),
		},
		66: {
			Fname:       __ccgo_ts + 23342,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4968,
		},
		67: {
			Fname:       __ccgo_ts + 9140,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9140,
		},
		68: {
			Fname:       __ccgo_ts + 23349,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_STR_TYPE10),
			Fvalue:      uintptr(unsafe.Pointer(&XDynamicMplu)),
		},
		69: {
			Fname:  __ccgo_ts + 23354,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XNextMode)),
		},
		70: {
			Fname:       __ccgo_ts + 12416,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12416,
		},
		71: {
			Fname:       __ccgo_ts + 23363,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4953,
		},
		72: {
			Fname:  __ccgo_ts + 23367,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XNumFullOmits)),
		},
		73: {
			Fname:  __ccgo_ts + 23380,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XNumPartialOmits)),
		},
		74: {
			Fname:  __ccgo_ts + 23396,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XNumQueued)),
		},
		75: {
			Fname:  __ccgo_ts + 23406,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XNumTriggered)),
		},
		76: {
			Fname:       __ccgo_ts + 12408,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12408,
		},
		77: {
			Fname:       __ccgo_ts + 23414,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4622,
		},
		78: {
			Fname:       __ccgo_ts + 23417,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		79: {
			Fname:       __ccgo_ts + 23426,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XParseUntriggered)),
			Fmax:        int32(1),
		},
		80: {
			Fname:       __ccgo_ts + 23443,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 1802,
		},
		81: {
			Fname:  __ccgo_ts + 23446,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDoPrefixLineNo)),
		},
		82: {
			Fname:  __ccgo_ts + 23459,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XPsCal)),
		},
		83: {
			Fname:  __ccgo_ts + 23465,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XOrigIterations)),
		},
		84: {
			Fname:  __ccgo_ts + 23472,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XRunDisabled)),
		},
		85: {
			Fname:       __ccgo_ts + 9181,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9181,
		},
		86: {
			Fname:       __ccgo_ts + 12398,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 12398,
		},
		87: {
			Fname:  __ccgo_ts + 23479,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XShaded)),
		},
		88: {
			Fname:  __ccgo_ts + 23486,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XDoSimpleCalendar)),
		},
		89: {
			Fname:  __ccgo_ts + 23496,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XSortByDate)),
		},
		90: {
			Fname:  __ccgo_ts + 23507,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XSortByPrio)),
		},
		91: {
			Fname:  __ccgo_ts + 23518,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XSortByTime)),
		},
		92: {
			Fname:       __ccgo_ts + 23529,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XSubsIndent)),
			Fmax:        int32(132),
		},
		93: {
			Fname:       __ccgo_ts + 9190,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9190,
		},
		94: {
			Fname:       __ccgo_ts + 23540,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XSuppressImplicitRemWarnings)),
			Fmax:        int32(1),
		},
		95: {
			Fname:       __ccgo_ts + 23565,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XSuppressLRM)),
			Fmax:        int32(1),
		},
		96: {
			Fname:  __ccgo_ts + 23577,
			Ftype1: int32(m_STR_TYPE10),
			Fvalue: uintptr(unsafe.Pointer(&XSysDir)),
		},
		97: {
			Fname:  __ccgo_ts + 2500,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		98: {
			Fname:  __ccgo_ts + 23588,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		99: {
			Fname:  __ccgo_ts + 2502,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		100: {
			Fname:  __ccgo_ts + 23591,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		101: {
			Fname:       __ccgo_ts + 23610,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_INT_TYPE9),
			Fvalue:      uintptr(unsafe.Pointer(&XTerminalHyperlinks)),
			Fmax:        int32(1),
		},
		102: {
			Fname:       __ccgo_ts + 9165,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9165,
		},
		103: {
			Fname:       __ccgo_ts + 23629,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		104: {
			Fname:  __ccgo_ts + 23637,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		105: {
			Fname:  __ccgo_ts + 2505,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		106: {
			Fname:       __ccgo_ts + 23650,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4538,
		},
		107: {
			Fname:  __ccgo_ts + 23656,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XTodoFilter)),
		},
		108: {
			Fname:       __ccgo_ts + 23667,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 4519,
		},
		109: {
			Fname:  __ccgo_ts + 23676,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		110: {
			Fname:  __ccgo_ts + 23679,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		111: {
			Fname:       __ccgo_ts + 9147,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9147,
		},
		112: {
			Fname:  __ccgo_ts + 2508,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		113: {
			Fname:  __ccgo_ts + 2511,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		114: {
			Fname:  __ccgo_ts + 23682,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		115: {
			Fname:  __ccgo_ts + 23684,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		116: {
			Fname:  __ccgo_ts + 23687,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		117: {
			Fname:  __ccgo_ts + 23690,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XUntimedBeforeTimed)),
		},
		118: {
			Fname:  __ccgo_ts + 23703,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XUse256Colors)),
		},
		119: {
			Fname:  __ccgo_ts + 23716,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XUseBGVTColors)),
		},
		120: {
			Fname:  __ccgo_ts + 23730,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XUseTrueColors)),
		},
		121: {
			Fname:  __ccgo_ts + 23744,
			Ftype1: int32(m_INT_TYPE9),
			Fvalue: uintptr(unsafe.Pointer(&XUseVTColors)),
		},
		122: {
			Fname:  __ccgo_ts + 23756,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		123: {
			Fname:  __ccgo_ts + 23759,
			Ftype1: int32(m_SPECIAL_TYPE1),
		},
		124: {
			Fname:       __ccgo_ts + 23762,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_SPECIAL_TYPE1),
		},
		125: {
			Fname:       __ccgo_ts + 23775,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 5095,
		},
		126: {
			Fname:       __ccgo_ts + 9155,
			Fmodifiable: uint8(1),
			Ftype1:      int32(m_TRANS_TYPE1),
			Fvalue:      __ccgo_ts + 9155,
		},
	}
	_VarStack = libc.UintptrFromInt32(0)
	XAddBlankLines = int32(1)
	XArgC = *new(int32)
	XArgV = *new(uintptr)
	XBanner = *new(TDynamicBuffer)
	XCalLines = int32(m_CAL_LINES)
	XCalMonths = *new(int32)
	XCalPad = int32(1)
	XCalSepLine = int32(1)
	XCalType = __ccgo_ts + 9135
	XCalWeeks = *new(int32)
	XCalWidth = int32(80)
	XCalculateUTC = int32(1)
	XCurDay = *new(int32)
	XCurLine = *new(uintptr)
	XCurMon = *new(int32)
	XCurYear = *new(int32)
	XDSEToday = *new(int32)
	XDaemon = *new(int32)
	XDaemonJSON = *new(int32)
	XDateSep = uint8('-')
	XDateTimeSep = uint8('@')
	XDayName = [7]uintptr{
		0: __ccgo_ts + 9140,
		1: __ccgo_ts + 9147,
		2: __ccgo_ts + 9155,
		3: __ccgo_ts + 9165,
		4: __ccgo_ts + 9174,
		5: __ccgo_ts + 9181,
		6: __ccgo_ts + 9190,
	}
	XDebugFlag = *new(int32)
	XDedupeReminders = *new(int32)
	XDefaultColorB = -int32(1)
	XDefaultColorG = -int32(1)
	XDefaultColorR = -int32(1)
	XDefaultDelta = *new(int32)
	XDefaultPrio = int32(m_NO_PRIORITY)
	XDefaultTDelta = *new(int32)
	XDeltaOverride = *new(int32)
	XDiagnosedExpression = *new(int32)
	XDidMsgReminder = *new(int32)
	XDoCalendar = *new(int32)
	XDoPrefixLineNo = *new(int32)
	XDoSimpleCalDelta = *new(int32)
	XDoSimpleCalendar = *new(int32)
	XDontFork = *new(int32)
	XDontIssueAts = *new(int32)
	XDontQueue = *new(int32)
	XDontSuppressQuoteMarkers = *new(int32)
	XDynamicHplu = __ccgo_ts + 4079
	XDynamicMplu = __ccgo_ts + 4079
	XEndSent = __ccgo_ts + 12448
	XEndSentIg = __ccgo_ts + 12434
	XErrFp = *new(uintptr)
	XErrMsg = [123]uintptr{
		0:   __ccgo_ts + 9221,
		1:   __ccgo_ts + 9224,
		2:   __ccgo_ts + 9236,
		3:   __ccgo_ts + 9250,
		4:   __ccgo_ts + 9273,
		5:   __ccgo_ts + 9292,
		6:   __ccgo_ts + 9304,
		7:   __ccgo_ts + 9323,
		8:   __ccgo_ts + 9341,
		9:   __ccgo_ts + 9362,
		10:  __ccgo_ts + 9376,
		11:  __ccgo_ts + 9394,
		12:  __ccgo_ts + 9439,
		13:  __ccgo_ts + 9475,
		14:  __ccgo_ts + 9488,
		15:  __ccgo_ts + 9502,
		16:  __ccgo_ts + 9516,
		17:  __ccgo_ts + 9554,
		18:  __ccgo_ts + 9571,
		19:  __ccgo_ts + 9590,
		20:  __ccgo_ts + 9613,
		21:  __ccgo_ts + 9636,
		22:  __ccgo_ts + 9646,
		23:  __ccgo_ts + 9693,
		24:  __ccgo_ts + 9708,
		25:  __ccgo_ts + 9731,
		26:  __ccgo_ts + 9752,
		27:  __ccgo_ts + 9771,
		28:  __ccgo_ts + 9787,
		29:  __ccgo_ts + 9803,
		30:  __ccgo_ts + 9818,
		31:  __ccgo_ts + 9834,
		32:  __ccgo_ts + 9869,
		33:  __ccgo_ts + 9881,
		34:  __ccgo_ts + 9903,
		35:  __ccgo_ts + 9923,
		36:  __ccgo_ts + 9948,
		37:  __ccgo_ts + 9974,
		38:  __ccgo_ts + 9999,
		39:  __ccgo_ts + 10027,
		40:  __ccgo_ts + 10079,
		41:  __ccgo_ts + 10092,
		42:  __ccgo_ts + 10105,
		43:  __ccgo_ts + 10124,
		44:  __ccgo_ts,
		45:  __ccgo_ts + 10158,
		46:  __ccgo_ts + 10188,
		47:  __ccgo_ts + 10233,
		48:  __ccgo_ts + 10271,
		49:  __ccgo_ts + 10316,
		50:  __ccgo_ts + 10361,
		51:  __ccgo_ts + 10382,
		52:  __ccgo_ts + 10404,
		53:  __ccgo_ts + 10424,
		54:  __ccgo_ts + 10438,
		55:  __ccgo_ts + 10473,
		56:  __ccgo_ts + 10494,
		57:  __ccgo_ts + 10526,
		58:  __ccgo_ts + 10587,
		59:  __ccgo_ts + 10607,
		60:  __ccgo_ts + 10629,
		61:  __ccgo_ts + 10649,
		62:  __ccgo_ts + 10689,
		63:  __ccgo_ts + 10712,
		64:  __ccgo_ts + 10728,
		65:  __ccgo_ts + 10752,
		66:  __ccgo_ts + 10790,
		67:  __ccgo_ts + 10835,
		68:  __ccgo_ts + 10864,
		69:  __ccgo_ts + 10892,
		70:  __ccgo_ts + 10919,
		71:  __ccgo_ts + 10951,
		72:  __ccgo_ts + 10975,
		73:  __ccgo_ts + 11008,
		74:  __ccgo_ts + 11038,
		75:  __ccgo_ts + 11071,
		76:  __ccgo_ts + 11080,
		77:  __ccgo_ts + 11086,
		78:  __ccgo_ts + 11098,
		79:  __ccgo_ts + 11114,
		80:  __ccgo_ts + 11129,
		81:  __ccgo_ts + 11137,
		82:  __ccgo_ts + 9818,
		83:  __ccgo_ts + 11179,
		84:  __ccgo_ts + 11221,
		85:  __ccgo_ts + 11245,
		86:  __ccgo_ts + 11265,
		87:  __ccgo_ts + 11283,
		88:  __ccgo_ts + 11310,
		89:  __ccgo_ts + 11337,
		90:  __ccgo_ts + 11367,
		91:  __ccgo_ts + 11384,
		92:  __ccgo_ts + 11406,
		93:  __ccgo_ts + 11425,
		94:  __ccgo_ts + 11458,
		95:  __ccgo_ts + 11482,
		96:  __ccgo_ts + 11496,
		97:  __ccgo_ts + 11535,
		98:  __ccgo_ts + 11552,
		99:  __ccgo_ts + 11576,
		100: __ccgo_ts + 11609,
		101: __ccgo_ts + 11633,
		102: __ccgo_ts + 11649,
		103: __ccgo_ts + 11670,
		104: __ccgo_ts + 11716,
		105: __ccgo_ts + 11739,
		106: __ccgo_ts + 11763,
		107: __ccgo_ts + 11797,
		108: __ccgo_ts + 11843,
		109: __ccgo_ts + 11883,
		110: __ccgo_ts + 11911,
		111: __ccgo_ts + 11946,
		112: __ccgo_ts + 11965,
		113: __ccgo_ts + 12001,
		114: __ccgo_ts + 12028,
		115: __ccgo_ts + 12067,
		116: __ccgo_ts + 12107,
		117: __ccgo_ts + 12167,
		118: __ccgo_ts + 12201,
		119: __ccgo_ts + 12236,
		120: __ccgo_ts + 12270,
		121: __ccgo_ts + 12306,
		122: __ccgo_ts + 12326,
	}
	XExprBuf = *new(uintptr)
	XExpressionEvaluationDisabled = *new(int32)
	XExpressionEvaluationTimeLimit = *new(int32)
	XExpressionNodeLimitPerLine = uint64(10000000)
	XExpressionNodesEvaluated = *new(uint64)
	XExpressionNodesEvaluatedThisLine = *new(uint64)
	XExpressionTimeLimitExceeded = *new(Tsig_atomic_t)
	XFileAccessDate = *new(int32)
	XFirstIndent = *new(int32)
	XFoldArray = [2][7]int32{
		0: {
			0: int32(2035),
			1: int32(2030),
			2: int32(2031),
			3: int32(2026),
			4: int32(2027),
			5: int32(2033),
			6: int32(2034),
		},
		1: {
			0: int32(2024),
			1: int32(2036),
			2: int32(2020),
			3: int32(2032),
			4: int32(2016),
			5: int32(2028),
			6: int32(2012),
		},
	}
	XFoldYear = *new(int32)
	XFormWidth = int32(72)
	XFreshLine = *new(int32)
	XFunc = [146]TBuiltinFunc{
		0: {
			Fname:    __ccgo_ts + 6607,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		1: {
			Fname:        __ccgo_ts + 6609,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		2: {
			Fname:    __ccgo_ts + 6613,
			Fminargs: uint8(2),
			Fmaxargs: uint8(2),
		},
		3: {
			Fname:    __ccgo_ts + 6620,
			Fmaxargs: uint8(1),
		},
		4: {
			Fname:    __ccgo_ts + 6626,
			Fmaxargs: uint8(1),
		},
		5: {
			Fname:        __ccgo_ts + 6632,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(4),
			Fis_constant: uint8(1),
		},
		6: {
			Fname:        __ccgo_ts + 6637,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(5),
			Fis_constant: uint8(1),
		},
		7: {
			Fname:    __ccgo_ts + 6647,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		8: {
			Fname:        __ccgo_ts + 6652,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		9: {
			Fname:        __ccgo_ts + 6656,
			Fis_constant: uint8(1),
		},
		10: {
			Fname:        __ccgo_ts + 6663,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(2),
			Fis_constant: uint8(1),
		},
		11: {
			Fname: __ccgo_ts + 6669,
		},
		12: {
			Fname:        __ccgo_ts + 6678,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		13: {
			Fname:        __ccgo_ts + 6683,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		14: {
			Fname:        __ccgo_ts + 6690,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		15: {
			Fname:        __ccgo_ts + 6700,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(2),
			Fis_constant: uint8(1),
		},
		16: {
			Fname:    __ccgo_ts + 6707,
			Fmaxargs: uint8(1),
		},
		17: {
			Fname:        __ccgo_ts + 5251,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		18: {
			Fname: __ccgo_ts + 6715,
		},
		19: {
			Fname:        __ccgo_ts + 6723,
			Fminargs:     uint8(3),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		20: {
			Fname:        __ccgo_ts + 6728,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		21: {
			Fname:        __ccgo_ts + 6737,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(5),
			Fis_constant: uint8(1),
		},
		22: {
			Fname:    __ccgo_ts + 6746,
			Fmaxargs: uint8(1),
		},
		23: {
			Fname:        __ccgo_ts + 4162,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		24: {
			Fname:        __ccgo_ts + 6751,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(2),
			Fis_constant: uint8(1),
		},
		25: {
			Fname:    __ccgo_ts + 6761,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		26: {
			Fname:    __ccgo_ts + 6769,
			Fminargs: uint8(1),
			Fmaxargs: uint8(3),
		},
		27: {
			Fname:    __ccgo_ts + 6777,
			Fmaxargs: uint8(1),
		},
		28: {
			Fname:    __ccgo_ts + 6782,
			Fmaxargs: uint8(1),
		},
		29: {
			Fname:        __ccgo_ts + 6793,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(2),
			Fis_constant: uint8(1),
		},
		30: {
			Fname:        __ccgo_ts + 6800,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		31: {
			Fname:    __ccgo_ts + 6805,
			Fminargs: uint8(1),
			Fmaxargs: uint8(2),
		},
		32: {
			Fname:    __ccgo_ts + 6814,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		33: {
			Fname:    __ccgo_ts + 6823,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		34: {
			Fname: __ccgo_ts + 6836,
		},
		35: {
			Fname: __ccgo_ts + 1617,
		},
		36: {
			Fname:    __ccgo_ts + 6844,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		37: {
			Fname:    __ccgo_ts + 6851,
			Fminargs: uint8(2),
			Fmaxargs: uint8(5),
		},
		38: {
			Fname:    __ccgo_ts + 6859,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		39: {
			Fname:    __ccgo_ts + 6866,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		40: {
			Fname:    __ccgo_ts + 6873,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		41: {
			Fname:        __ccgo_ts + 6881,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		42: {
			Fname:        __ccgo_ts + 4975,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		43: {
			Fname:        __ccgo_ts + 6885,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		44: {
			Fname:        __ccgo_ts + 6896,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		45: {
			Fname:        __ccgo_ts + 6910,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		46: {
			Fname:        __ccgo_ts + 6914,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		47: {
			Fname:        __ccgo_ts + 6920,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		48: {
			Fname:        __ccgo_ts + 6926,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		49: {
			Fname:    __ccgo_ts + 6934,
			Fmaxargs: uint8(2),
		},
		50: {
			Fname:        __ccgo_ts + 6940,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		51: {
			Fname:    __ccgo_ts + 6947,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		52: {
			Fname:    __ccgo_ts + 6957,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		53: {
			Fname:        __ccgo_ts + 5902,
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		54: {
			Fname:        __ccgo_ts + 6966,
			Fis_constant: uint8(1),
		},
		55: {
			Fname:        __ccgo_ts + 6975,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		56: {
			Fname:        __ccgo_ts + 6986,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		57: {
			Fname:        __ccgo_ts + 6992,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		58: {
			Fname:        __ccgo_ts + 6996,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		59: {
			Fname:        __ccgo_ts + 7003,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		60: {
			Fname:        __ccgo_ts + 7011,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		61: {
			Fname:        __ccgo_ts + 7019,
			Fminargs:     uint8(3),
			Fmaxargs:     uint8(4),
			Fis_constant: uint8(1),
		},
		62: {
			Fname:        __ccgo_ts + 7025,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		63: {
			Fname:        __ccgo_ts + 7034,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		64: {
			Fname:        __ccgo_ts + 7043,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		65: {
			Fname:        __ccgo_ts + 7051,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(m_NO_MAX_ARGS),
			Fis_constant: uint8(1),
		},
		66: {
			Fname:    __ccgo_ts + 7055,
			Fmaxargs: uint8(2),
		},
		67: {
			Fname:        __ccgo_ts + 4968,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		68: {
			Fname:        __ccgo_ts + 7067,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		69: {
			Fname:        __ccgo_ts + 7071,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		70: {
			Fname:    __ccgo_ts + 7078,
			Fminargs: uint8(1),
			Fmaxargs: uint8(3),
		},
		71: {
			Fname:    __ccgo_ts + 7087,
			Fminargs: uint8(1),
			Fmaxargs: uint8(3),
		},
		72: {
			Fname:    __ccgo_ts + 7100,
			Fmaxargs: uint8(2),
		},
		73: {
			Fname:    __ccgo_ts + 7110,
			Fmaxargs: uint8(1),
		},
		74: {
			Fname:    __ccgo_ts + 7119,
			Fmaxargs: uint8(1),
		},
		75: {
			Fname:    __ccgo_ts + 7131,
			Fmaxargs: uint8(1),
		},
		76: {
			Fname:    __ccgo_ts + 7139,
			Fmaxargs: uint8(1),
		},
		77: {
			Fname:    __ccgo_ts + 7150,
			Fminargs: uint8(1),
			Fmaxargs: uint8(3),
		},
		78: {
			Fname:    __ccgo_ts + 7159,
			Fminargs: uint8(1),
			Fmaxargs: uint8(m_NO_MAX_ARGS),
		},
		79: {
			Fname:    __ccgo_ts + 7169,
			Fmaxargs: uint8(1),
		},
		80: {
			Fname:    __ccgo_ts + 7175,
			Fmaxargs: uint8(1),
		},
		81: {
			Fname:    __ccgo_ts + 7181,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		82: {
			Fname:    __ccgo_ts + 7190,
			Fminargs: uint8(2),
			Fmaxargs: uint8(m_NO_MAX_ARGS),
		},
		83: {
			Fname: __ccgo_ts + 4953,
		},
		84: {
			Fname:        __ccgo_ts + 7201,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		85: {
			Fname:    __ccgo_ts + 7205,
			Fmaxargs: uint8(1),
		},
		86: {
			Fname:        __ccgo_ts + 7220,
			Fis_constant: uint8(1),
		},
		87: {
			Fname:        __ccgo_ts + 7227,
			Fminargs:     uint8(3),
			Fmaxargs:     uint8(4),
			Fis_constant: uint8(1),
		},
		88: {
			Fname:        __ccgo_ts + 7231,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		89: {
			Fname:        __ccgo_ts + 7238,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(4),
			Fis_constant: uint8(1),
		},
		90: {
			Fname:        __ccgo_ts + 7245,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		91: {
			Fname: __ccgo_ts + 7253,
		},
		92: {
			Fname: __ccgo_ts + 7265,
		},
		93: {
			Fname: __ccgo_ts + 7273,
		},
		94: {
			Fname: __ccgo_ts + 7283,
		},
		95: {
			Fname:        __ccgo_ts + 7288,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		96: {
			Fname:    __ccgo_ts + 7292,
			Fminargs: uint8(1),
			Fmaxargs: uint8(2),
		},
		97: {
			Fname:        __ccgo_ts + 7298,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		98: {
			Fname:    __ccgo_ts + 7310,
			Fminargs: uint8(2),
			Fmaxargs: uint8(m_NO_MAX_ARGS),
		},
		99: {
			Fname:    __ccgo_ts + 7316,
			Fminargs: uint8(1),
			Fmaxargs: uint8(2),
		},
		100: {
			Fname: __ccgo_ts + 7322,
		},
		101: {
			Fname:        __ccgo_ts + 7329,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		102: {
			Fname:        __ccgo_ts + 7336,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(3),
			Fis_constant: uint8(1),
		},
		103: {
			Fname:    __ccgo_ts + 7343,
			Fmaxargs: uint8(1),
		},
		104: {
			Fname:    __ccgo_ts + 7351,
			Fmaxargs: uint8(1),
		},
		105: {
			Fname:        __ccgo_ts + 1269,
			Fminargs:     uint8(2),
			Fmaxargs:     uint8(2),
			Fis_constant: uint8(1),
		},
		106: {
			Fname:        __ccgo_ts + 7358,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		107: {
			Fname:    __ccgo_ts + 7367,
			Fmaxargs: uint8(1),
		},
		108: {
			Fname: __ccgo_ts + 4538,
		},
		109: {
			Fname:    __ccgo_ts + 7376,
			Fmaxargs: uint8(m_NO_MAX_ARGS),
		},
		110: {
			Fname: __ccgo_ts + 7381,
		},
		111: {
			Fname: __ccgo_ts + 7390,
		},
		112: {
			Fname: __ccgo_ts + 7399,
		},
		113: {
			Fname: __ccgo_ts + 2478,
		},
		114: {
			Fname: __ccgo_ts + 2487,
		},
		115: {
			Fname: __ccgo_ts + 7419,
		},
		116: {
			Fname: __ccgo_ts + 7429,
		},
		117: {
			Fname: __ccgo_ts + 7442,
		},
		118: {
			Fname: __ccgo_ts + 7460,
		},
		119: {
			Fname: __ccgo_ts + 7475,
		},
		120: {
			Fname: __ccgo_ts + 7492,
		},
		121: {
			Fname:    __ccgo_ts + 7501,
			Fminargs: uint8(1),
			Fmaxargs: uint8(3),
		},
		122: {
			Fname:    __ccgo_ts + 7509,
			Fminargs: uint8(1),
			Fmaxargs: uint8(1),
		},
		123: {
			Fname: __ccgo_ts + 7518,
		},
		124: {
			Fname: __ccgo_ts + 7529,
		},
		125: {
			Fname: __ccgo_ts + 7544,
		},
		126: {
			Fname: __ccgo_ts + 7557,
		},
		127: {
			Fname: __ccgo_ts + 7565,
		},
		128: {
			Fname: __ccgo_ts + 7578,
		},
		129: {
			Fname: __ccgo_ts + 7587,
		},
		130: {
			Fname: __ccgo_ts + 7596,
		},
		131: {
			Fname: __ccgo_ts + 7610,
		},
		132: {
			Fname: __ccgo_ts + 7622,
		},
		133: {
			Fname: __ccgo_ts + 7633,
		},
		134: {
			Fname: __ccgo_ts + 7640,
		},
		135: {
			Fname: __ccgo_ts + 7650,
		},
		136: {
			Fname:        __ccgo_ts + 7660,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		137: {
			Fname:    __ccgo_ts + 7667,
			Fminargs: uint8(2),
			Fmaxargs: uint8(3),
		},
		138: {
			Fname:        __ccgo_ts + 7677,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		139: {
			Fname:        __ccgo_ts + 7683,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		140: {
			Fname:        __ccgo_ts + 7694,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(2),
			Fis_constant: uint8(1),
		},
		141: {
			Fname:        __ccgo_ts + 7700,
			Fis_constant: uint8(1),
		},
		142: {
			Fname:    __ccgo_ts + 7708,
			Fmaxargs: uint8(3),
		},
		143: {
			Fname:        __ccgo_ts + 7715,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		144: {
			Fname:        __ccgo_ts + 7721,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
		145: {
			Fname:        __ccgo_ts + 804,
			Fminargs:     uint8(1),
			Fmaxargs:     uint8(1),
			Fis_constant: uint8(1),
		},
	}
	XFuncHash = *new(Thash_table)
	XFuncRecursionLevel = *new(uint32)
	XHideCompletedTodos = *new(int32)
	XHush = *new(int32)
	XIgnoreOnce = *new(int32)
	XInfiniteDelta = *new(int32)
	XInitialFile = *new(uintptr)
	XIterations = int32(1)
	XJSONLinesEmitted = *new(int32)
	XJSONMode = *new(int32)
	XLastTimeTrig = *new(TTimeTrig)
	XLastTrigValid = *new(int32)
	XLastTrigger = *new(TTrigger)
	XLastTriggerDate = *new(int32)
	XLastTriggerTime = int32(m_INT_MAX2)
	XLatDeg = *new(int32)
	XLatMin = *new(int32)
	XLatSec = *new(int32)
	XLatitude = float64(m_DEFAULT_LATITUDE)
	XLineBuffer = *new(TDynamicBuffer)
	XLineNo = *new(int32)
	XLineNoStart = *new(int32)
	XLocalDSEToday = *new(int32)
	XLocalSysTime = -int32(1)
	XLocalTimeZone = *new(uintptr)
	XLocation = __ccgo_ts + 12441
	XLongDeg = *new(int32)
	XLongMin = *new(int32)
	XLongSec = *new(int32)
	XLongitude = -libc.Float64FromFloat64(75.68944444444445)
	XMaxCachedLines = int32(1000000)
	XMaxExprNodeFilename = *new(uintptr)
	XMaxExprNodeLineNo = *new(int32)
	XMaxExprNodesPerLine = *new(uint64)
	XMaxIncludeCmdLines = int32(10000)
	XMaxLateMinutes = *new(int32)
	XMaxLineLength = int32(10485760)
	XMaxSatIter = int32(10000)
	XMaxStringLen = int32(m_MAX_STR_LEN)
	XMinsFromUTC = *new(int32)
	XMondayFirst = *new(int32)
	XMonthDays = [12]int32{
		0:  int32(31),
		1:  int32(29),
		2:  int32(31),
		3:  int32(30),
		4:  int32(31),
		5:  int32(30),
		6:  int32(31),
		7:  int32(31),
		8:  int32(30),
		9:  int32(31),
		10: int32(30),
		11: int32(31),
	}
	XMonthIndex = [2][12]int32{
		0: {
			1:  int32(31),
			2:  int32(59),
			3:  int32(90),
			4:  int32(120),
			5:  int32(151),
			6:  int32(181),
			7:  int32(212),
			8:  int32(243),
			9:  int32(273),
			10: int32(304),
			11: int32(334),
		},
		1: {
			1:  int32(31),
			2:  int32(60),
			3:  int32(91),
			4:  int32(121),
			5:  int32(152),
			6:  int32(182),
			7:  int32(213),
			8:  int32(244),
			9:  int32(274),
			10: int32(305),
			11: int32(335),
		},
	}
	XMonthName = [12]uintptr{
		0:  __ccgo_ts + 12348,
		1:  __ccgo_ts + 12356,
		2:  __ccgo_ts + 12365,
		3:  __ccgo_ts + 12371,
		4:  __ccgo_ts + 12377,
		5:  __ccgo_ts + 12381,
		6:  __ccgo_ts + 12386,
		7:  __ccgo_ts + 12391,
		8:  __ccgo_ts + 12398,
		9:  __ccgo_ts + 12408,
		10: __ccgo_ts + 12416,
		11: __ccgo_ts + 12425,
	}
	XMsgCommand = *new(uintptr)
	XNextMode = *new(int32)
	XNoFormat = *new(int32)
	XNumErrs = libc.Int32FromUint64(libc.Uint64FromInt64(984) / libc.Uint64FromInt64(8))
	XNumFullOmits = *new(int32)
	XNumFuncs = libc.Int32FromUint64(libc.Uint64FromInt64(4672) / libc.Uint64FromInt64(32))
	XNumPartialOmits = *new(int32)
	XNumQueued = *new(int32)
	XNumTriggered = *new(int32)
	XNumTrustedUsers = *new(int32)
	XOnceDate = -int32(1)
	XOnceFile = *new(uintptr)
	XOrigIterations = *new(int32)
	XParseUntriggered = *new(int32)
	XProcessedOnce = *new(int32)
	XPsCal = *new(int32)
	XPurgeFP = *new(uintptr)
	XPurgeIncludeDepth = *new(int32)
	XPurgeMode = *new(int32)
	XQueuedMsgCommand = *new(uintptr)
	XRealToday = *new(int32)
	XRunDisabled = *new(int32)
	XScFormat = *new(int32)
	XShaded = *new(int32)
	XShouldCache = *new(int32)
	XShowAllErrors = *new(int32)
	XSortByDate = *new(int32)
	XSortByPrio = *new(int32)
	XSortByTime = *new(int32)
	XSubsIndent = *new(int32)
	XSuppressErrorOutputInCatch = *new(int32)
	XSuppressImplicitRemWarnings = *new(int32)
	XSuppressLRM = *new(int32)
	XSynthesizeTags = *new(int32)
	XSysDir = __ccgo_ts + 9197
	XSysTime = -int32(1)
	XTerminalBackground = -int32(1)
	XTerminalHyperlinks = -int32(1)
	XTestMode = *new(int32)
	XTimeSep = uint8(':')
	XTodoFilter = *new(int32)
	XTokArray = [92]TToken{
		0: {
			Fname:   __ccgo_ts + 1601,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_AddOmit),
		},
		1: {
			Fname:   __ccgo_ts + 20064,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Skip),
			Fval:    int32(m_AFTER_SKIP),
		},
		2: {
			Fname:   __ccgo_ts + 20070,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(3),
		},
		3: {
			Fname:   __ccgo_ts + 5089,
			FMinLen: uint8(2),
			Ftype1:  int32(_T_At),
		},
		4: {
			Fname:   __ccgo_ts + 20076,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(7),
		},
		5: {
			Fname:   __ccgo_ts + 20083,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Banner),
		},
		6: {
			Fname:   __ccgo_ts + 20090,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_Skip),
			Fval:    int32(m_BEFORE_SKIP),
		},
		7: {
			Fname:   __ccgo_ts + 20097,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_CAL_TYPE),
		},
		8: {
			Fname:   __ccgo_ts + 20101,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Clr),
		},
		9: {
			Fname:   __ccgo_ts + 20120,
			FMinLen: uint8(16),
			Ftype1:  int32(_T_CompleteThrough),
		},
		10: {
			Fname:   __ccgo_ts + 20137,
			FMinLen: uint8(17),
			Ftype1:  int32(_T_CompleteThrough),
		},
		11: {
			Fname:   __ccgo_ts + 20155,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Debug),
		},
		12: {
			Fname:   __ccgo_ts + 20161,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(11),
		},
		13: {
			Fname:   __ccgo_ts + 20170,
			FMinLen: uint8(2),
			Ftype1:  int32(_T_IncludeR),
		},
		14: {
			Fname:   __ccgo_ts + 20173,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Dumpvars),
		},
		15: {
			Fname:   __ccgo_ts + 1316,
			FMinLen: uint8(8),
			Ftype1:  int32(_T_Duration),
		},
		16: {
			Fname:   __ccgo_ts + 20182,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Else),
		},
		17: {
			Fname:   __ccgo_ts + 20187,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_EndIf),
		},
		18: {
			Fname:   __ccgo_ts + 20193,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_ErrMsg),
		},
		19: {
			Fname:   __ccgo_ts + 20200,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Exit),
		},
		20: {
			Fname:   __ccgo_ts + 20205,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Expr),
		},
		21: {
			Fname:   __ccgo_ts + 20210,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(1),
		},
		22: {
			Fname:   __ccgo_ts + 20219,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Ordinal),
		},
		23: {
			Fname:   __ccgo_ts + 16417,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Flush),
		},
		24: {
			Fname:   __ccgo_ts + 20225,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_FORMATTED_TYPE),
		},
		25: {
			Fname:   __ccgo_ts + 20229,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_Ordinal),
			Fval:    int32(3),
		},
		26: {
			Fname:   __ccgo_ts + 20236,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_Frename),
		},
		27: {
			Fname:   __ccgo_ts + 20244,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
			Fval:    int32(4),
		},
		28: {
			Fname:   __ccgo_ts + 1498,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Scanfrom),
			Fval:    int32(m_FROM_TYPE),
		},
		29: {
			Fname:   __ccgo_ts + 20251,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Fset),
		},
		30: {
			Fname:   __ccgo_ts + 20256,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_Funset),
		},
		31: {
			Fname:   __ccgo_ts + 20263,
			FMinLen: uint8(2),
			Ftype1:  int32(_T_If),
		},
		32: {
			Fname:   __ccgo_ts + 20266,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_IfTrig),
		},
		33: {
			Fname:   __ccgo_ts + 20273,
			FMinLen: uint8(2),
			Ftype1:  int32(_T_In),
		},
		34: {
			Fname:   __ccgo_ts + 20276,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Include),
		},
		35: {
			Fname:   __ccgo_ts + 20284,
			FMinLen: uint8(10),
			Ftype1:  int32(_T_IncludeCmd),
		},
		36: {
			Fname:   __ccgo_ts + 20295,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Info),
		},
		37: {
			Fname:   __ccgo_ts + 20300,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
		},
		38: {
			Fname:   __ccgo_ts + 20308,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(6),
		},
		39: {
			Fname:   __ccgo_ts + 20313,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(5),
		},
		40: {
			Fname:   __ccgo_ts + 20318,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Ordinal),
			Fval:    -int32(1),
		},
		41: {
			Fname:   __ccgo_ts + 20323,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_BackAdj),
			Fval:    -int32(1),
		},
		42: {
			Fname:   __ccgo_ts + 20331,
			FMinLen: uint8(11),
			Ftype1:  int32(_T_BackAdj),
			Fval:    int32(1),
		},
		43: {
			Fname:   __ccgo_ts + 20343,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(2),
		},
		44: {
			Fname:   __ccgo_ts + 20349,
			FMinLen: uint8(11),
			Ftype1:  int32(_T_MaxOverdue),
		},
		45: {
			Fname:   __ccgo_ts + 20361,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(4),
		},
		46: {
			Fname:   __ccgo_ts + 20365,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_MaybeUncomputable),
		},
		47: {
			Fname:   __ccgo_ts + 20384,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
		},
		48: {
			Fname:   __ccgo_ts + 20391,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_MSF_TYPE),
		},
		49: {
			Fname:   __ccgo_ts + 20395,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_MSG_TYPE),
		},
		50: {
			Fname:   __ccgo_ts + 1573,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_NoQueue),
		},
		51: {
			Fname:   __ccgo_ts + 20399,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(10),
		},
		52: {
			Fname:   __ccgo_ts + 20408,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(9),
		},
		53: {
			Fname:   __ccgo_ts + 20416,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Omit),
		},
		54: {
			Fname:   __ccgo_ts + 1592,
			FMinLen: uint8(8),
			Ftype1:  int32(_T_OmitFunc),
		},
		55: {
			Fname:   __ccgo_ts + 1472,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Once),
		},
		56: {
			Fname:   __ccgo_ts + 20421,
			FMinLen: uint8(9),
			Ftype1:  int32(_T_PopFuncs),
		},
		57: {
			Fname:   __ccgo_ts + 20431,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Pop),
		},
		58: {
			Fname:   __ccgo_ts + 20448,
			FMinLen: uint8(8),
			Ftype1:  int32(_T_PopVars),
		},
		59: {
			Fname:   __ccgo_ts + 20457,
			FMinLen: uint8(8),
			Ftype1:  int32(_T_Preserve),
		},
		60: {
			Fname:   __ccgo_ts + 1503,
			FMinLen: uint8(8),
			Ftype1:  int32(_T_Priority),
		},
		61: {
			Fname:   __ccgo_ts + 20466,
			FMinLen: uint8(2),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_PS_TYPE),
		},
		62: {
			Fname:   __ccgo_ts + 20469,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_PSF_TYPE),
		},
		63: {
			Fname:   __ccgo_ts + 20476,
			FMinLen: uint8(10),
			Ftype1:  int32(_T_PushFuncs),
		},
		64: {
			Fname:   __ccgo_ts + 20487,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Push),
		},
		65: {
			Fname:   __ccgo_ts + 20505,
			FMinLen: uint8(9),
			Ftype1:  int32(_T_PushVars),
		},
		66: {
			Fname:   __ccgo_ts + 13451,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Rem),
		},
		67: {
			Fname:   __ccgo_ts + 20515,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_Return),
		},
		68: {
			Fname:   __ccgo_ts + 20522,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_RUN_TYPE),
		},
		69: {
			Fname:   __ccgo_ts + 20526,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_SAT_TYPE),
		},
		70: {
			Fname:   __ccgo_ts + 20534,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
			Fval:    int32(5),
		},
		71: {
			Fname:   __ccgo_ts + 1477,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Scanfrom),
		},
		72: {
			Fname:   __ccgo_ts + 1581,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Sched),
		},
		73: {
			Fname:   __ccgo_ts + 20543,
			FMinLen: uint8(6),
			Ftype1:  int32(_T_Ordinal),
			Fval:    int32(1),
		},
		74: {
			Fname:   __ccgo_ts + 20550,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Month),
			Fval:    int32(8),
		},
		75: {
			Fname:   __ccgo_ts + 20560,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Set),
		},
		76: {
			Fname:   __ccgo_ts + 1443,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Skip),
			Fval:    int32(m_SKIP_SKIP),
		},
		77: {
			Fname:   __ccgo_ts + 20564,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_RemType),
			Fval:    int32(m_PASSTHRU_TYPE),
		},
		78: {
			Fname:   __ccgo_ts + 20572,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
			Fval:    int32(6),
		},
		79: {
			Fname:   __ccgo_ts + 20579,
			FMinLen: uint8(10),
			Ftype1:  int32(_T_IncludeSys),
		},
		80: {
			Fname:   __ccgo_ts + 20590,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_Tag),
		},
		81: {
			Fname:   __ccgo_ts + 20594,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Ordinal),
			Fval:    int32(2),
		},
		82: {
			Fname:   __ccgo_ts + 20600,
			FMinLen: uint8(7),
			Ftype1:  int32(_T_Through),
		},
		83: {
			Fname:   __ccgo_ts + 20608,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
			Fval:    int32(3),
		},
		84: {
			Fname:   __ccgo_ts + 20617,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Todo),
		},
		85: {
			Fname:   __ccgo_ts + 19689,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Translate),
		},
		86: {
			Fname:   __ccgo_ts + 20622,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
			Fval:    int32(1),
		},
		87: {
			Fname:   __ccgo_ts + 1614,
			FMinLen: uint8(2),
			Ftype1:  int32(_T_Tz),
		},
		88: {
			Fname:   __ccgo_ts + 20630,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_UnSet),
		},
		89: {
			Fname:   __ccgo_ts + 1466,
			FMinLen: uint8(5),
			Ftype1:  int32(_T_Until),
		},
		90: {
			Fname:   __ccgo_ts + 1587,
			FMinLen: uint8(4),
			Ftype1:  int32(_T_Warn),
		},
		91: {
			Fname:   __ccgo_ts + 20636,
			FMinLen: uint8(3),
			Ftype1:  int32(_T_WkDay),
			Fval:    int32(2),
		},
	}
	XTranslationTable = *new(Thash_table)
	XTrustedUsers = *new([20]Tuid_t)
	XUntimedBeforeTimed = *new(int32)
	XUse256Colors = *new(int32)
	XUseBGVTColors = *new(int32)
	XUseStdin = *new(int32)
	XUseTrueColors = *new(int32)
	XUseUTF8Chars = *new(int32)
	XUseVTChars = *new(int32)
	XUseVTColors = *new(int32)
	XWarned = *new(int32)
	XWarnedAboutImplicit = *new(int32)
	XWarningLevel = *new(uintptr)
	XWeekdayOmits = *new(int32)
	Xcwts = [76]uint8{
		0:  uint8(0x46),
		1:  uint8(0x75),
		2:  uint8(0x63),
		3:  uint8(0x6b),
		4:  uint8(0x20),
		5:  uint8(0x74),
		6:  uint8(0x68),
		7:  uint8(0x6f),
		8:  uint8(0x73),
		9:  uint8(0x65),
		10: uint8(0x20),
		11: uint8(0x74),
		12: uint8(0x72),
		13: uint8(0x61),
		14: uint8(0x6e),
		15: uint8(0x73),
		16: uint8(0x70),
		17: uint8(0x68),
		18: uint8(0x6f),
		19: uint8(0x62),
		20: uint8(0x69),
		21: uint8(0x63),
		22: uint8(0x20),
		23: uint8(0x41),
		24: uint8(0x6d),
		25: uint8(0x65),
		26: uint8(0x72),
		27: uint8(0x69),
		28: uint8(0x63),
		29: uint8(0x61),
		30: uint8(0x6e),
		31: uint8(0x20),
		32: uint8(0x52),
		33: uint8(0x65),
		34: uint8(0x70),
		35: uint8(0x75),
		36: uint8(0x62),
		37: uint8(0x6c),
		38: uint8(0x69),
		39: uint8(0x63),
		40: uint8(0x61),
		41: uint8(0x6e),
		42: uint8(0x73),
		43: uint8(0x2e),
		44: uint8(0x20),
		45: uint8(0x20),
		46: uint8(0x54),
		47: uint8(0x72),
		48: uint8(0x61),
		49: uint8(0x6e),
		50: uint8(0x73),
		51: uint8(0x20),
		52: uint8(0x72),
		53: uint8(0x69),
		54: uint8(0x67),
		55: uint8(0x68),
		56: uint8(0x74),
		57: uint8(0x73),
		58: uint8(0x20),
		59: uint8(0x61),
		60: uint8(0x72),
		61: uint8(0x65),
		62: uint8(0x20),
		63: uint8(0x68),
		64: uint8(0x75),
		65: uint8(0x6d),
		66: uint8(0x61),
		67: uint8(0x6e),
		68: uint8(0x20),
		69: uint8(0x72),
		70: uint8(0x69),
		71: uint8(0x67),
		72: uint8(0x68),
		73: uint8(0x74),
		74: uint8(0x73),
		75: uint8(0x2e),
	}
	Xtranslatables = [97]uintptr{
		0:  __ccgo_ts + 2417,
		1:  __ccgo_ts + 2337,
		2:  __ccgo_ts + 22115,
		3:  __ccgo_ts + 13152,
		4:  __ccgo_ts + 21805,
		5:  __ccgo_ts + 23880,
		6:  __ccgo_ts + 22010,
		7:  __ccgo_ts + 6317,
		8:  __ccgo_ts + 6207,
		9:  __ccgo_ts + 21788,
		10: __ccgo_ts + 6175,
		11: __ccgo_ts + 6452,
		12: __ccgo_ts + 6043,
		13: __ccgo_ts + 18799,
		14: __ccgo_ts + 9057,
		15: __ccgo_ts + 22476,
		16: __ccgo_ts + 21359,
		17: __ccgo_ts + 2025,
		18: __ccgo_ts + 18460,
		19: __ccgo_ts + 6392,
		20: __ccgo_ts + 6237,
		21: __ccgo_ts + 4081,
		22: __ccgo_ts + 21483,
		23: __ccgo_ts + 21537,
		24: __ccgo_ts + 12962,
		25: __ccgo_ts + 5115,
		26: __ccgo_ts + 21785,
		27: __ccgo_ts + 21302,
		28: __ccgo_ts + 21009,
		29: __ccgo_ts + 20701,
		30: __ccgo_ts + 3145,
		31: __ccgo_ts + 13123,
		32: __ccgo_ts + 4417,
		33: __ccgo_ts + 21888,
		34: __ccgo_ts + 5185,
		35: __ccgo_ts + 5257,
		36: __ccgo_ts + 8057,
		37: __ccgo_ts + 22225,
		38: __ccgo_ts + 18321,
		39: __ccgo_ts + 3100,
		40: __ccgo_ts + 21667,
		41: __ccgo_ts + 18223,
		42: __ccgo_ts + 23819,
		43: __ccgo_ts + 21400,
		44: __ccgo_ts + 22403,
		45: __ccgo_ts + 6084,
		46: __ccgo_ts + 6140,
		47: __ccgo_ts + 6113,
		48: __ccgo_ts + 6355,
		49: __ccgo_ts + 3654,
		50: __ccgo_ts + 2514,
		51: __ccgo_ts + 2553,
		52: __ccgo_ts + 2593,
		53: __ccgo_ts + 6476,
		54: __ccgo_ts + 6552,
		55: __ccgo_ts + 6277,
		56: __ccgo_ts + 5450,
		57: __ccgo_ts + 22686,
		58: __ccgo_ts + 2309,
		59: __ccgo_ts + 21730,
		60: __ccgo_ts + 18185,
		61: __ccgo_ts + 23779,
		62: __ccgo_ts + 1083,
		63: __ccgo_ts + 5369,
		64: __ccgo_ts + 22523,
		65: __ccgo_ts + 3210,
		66: __ccgo_ts + 3270,
		67: __ccgo_ts + 3329,
		68: __ccgo_ts + 21609,
		69: __ccgo_ts + 3055,
		70: __ccgo_ts + 8993,
		71: __ccgo_ts + 3437,
		72: __ccgo_ts + 3488,
		73: __ccgo_ts + 3385,
		74: __ccgo_ts + 17547,
		75: __ccgo_ts + 4306,
		76: __ccgo_ts + 4254,
		77: __ccgo_ts + 4365,
		78: __ccgo_ts + 3543,
		79: __ccgo_ts + 22586,
		80: __ccgo_ts + 18393,
		81: __ccgo_ts + 5907,
		82: __ccgo_ts + 4553,
		83: __ccgo_ts + 22298,
		84: __ccgo_ts + 22350,
		85: __ccgo_ts + 5099,
		86: __ccgo_ts + 4166,
		87: __ccgo_ts + 22763,
		88: __ccgo_ts + 5566,
		89: __ccgo_ts + 4948,
		90: __ccgo_ts + 5681,
		91: __ccgo_ts + 8568,
		92: __ccgo_ts + 8238,
		93: __ccgo_ts + 21843,
		94: __ccgo_ts + 5103,
		95: __ccgo_ts + 4528,
		96: libc.UintptrFromInt32(0),
	}
	Xwatch_fd = -int32(1)
	{
		p := unsafe.Pointer(&XFunc)
		*(*uintptr)(unsafe.Add(p, 16)) = __ccgo_fp(_F_)
		*(*uintptr)(unsafe.Add(p, 48)) = __ccgo_fp(_FAbs)
		*(*uintptr)(unsafe.Add(p, 80)) = __ccgo_fp(_FAccess)
		*(*uintptr)(unsafe.Add(p, 112)) = __ccgo_fp(_FADawn)
		*(*uintptr)(unsafe.Add(p, 144)) = __ccgo_fp(_FADusk)
		*(*uintptr)(unsafe.Add(p, 176)) = __ccgo_fp(_FAmpm)
		*(*uintptr)(unsafe.Add(p, 208)) = __ccgo_fp(_FAnsicolor)
		*(*uintptr)(unsafe.Add(p, 240)) = __ccgo_fp(_FArgs)
		*(*uintptr)(unsafe.Add(p, 272)) = __ccgo_fp(_FAsc)
		*(*uintptr)(unsafe.Add(p, 304)) = __ccgo_fp(_FBaseyr)
		*(*uintptr)(unsafe.Add(p, 344)) = __ccgo_fp(_FCatch)
		*(*uintptr)(unsafe.Add(p, 368)) = __ccgo_fp(_FCatchErr)
		*(*uintptr)(unsafe.Add(p, 400)) = __ccgo_fp(_FChar)
		*(*uintptr)(unsafe.Add(p, 440)) = __ccgo_fp(_FChoose)
		*(*uintptr)(unsafe.Add(p, 464)) = __ccgo_fp(_FCodepoint)
		*(*uintptr)(unsafe.Add(p, 496)) = __ccgo_fp(_FCoerce)
		*(*uintptr)(unsafe.Add(p, 528)) = __ccgo_fp(_FColumns)
		*(*uintptr)(unsafe.Add(p, 560)) = __ccgo_fp(_FNonconst)
		*(*uintptr)(unsafe.Add(p, 592)) = __ccgo_fp(_FCurrent)
		*(*uintptr)(unsafe.Add(p, 624)) = __ccgo_fp(_FDate)
		*(*uintptr)(unsafe.Add(p, 656)) = __ccgo_fp(_FDatepart)
		*(*uintptr)(unsafe.Add(p, 688)) = __ccgo_fp(_FDateTime)
		*(*uintptr)(unsafe.Add(p, 720)) = __ccgo_fp(_FDawn)
		*(*uintptr)(unsafe.Add(p, 752)) = __ccgo_fp(_FDay)
		*(*uintptr)(unsafe.Add(p, 784)) = __ccgo_fp(_FDaysinmon)
		*(*uintptr)(unsafe.Add(p, 816)) = __ccgo_fp(_FDefined)
		*(*uintptr)(unsafe.Add(p, 848)) = __ccgo_fp(_FDosubst)
		*(*uintptr)(unsafe.Add(p, 880)) = __ccgo_fp(_FDusk)
		*(*uintptr)(unsafe.Add(p, 912)) = __ccgo_fp(_FEasterdate)
		*(*uintptr)(unsafe.Add(p, 944)) = __ccgo_fp(_FEscape)
		*(*uintptr)(unsafe.Add(p, 976)) = __ccgo_fp(_FEval)
		*(*uintptr)(unsafe.Add(p, 1008)) = __ccgo_fp(_FEvalTrig)
		*(*uintptr)(unsafe.Add(p, 1040)) = __ccgo_fp(_FFiledate)
		*(*uintptr)(unsafe.Add(p, 1072)) = __ccgo_fp(_FFiledatetime)
		*(*uintptr)(unsafe.Add(p, 1104)) = __ccgo_fp(_FFiledir)
		*(*uintptr)(unsafe.Add(p, 1136)) = __ccgo_fp(_FFilename)
		*(*uintptr)(unsafe.Add(p, 1168)) = __ccgo_fp(_FGetenv)
		*(*uintptr)(unsafe.Add(p, 1200)) = __ccgo_fp(_FHebdate)
		*(*uintptr)(unsafe.Add(p, 1232)) = __ccgo_fp(_FHebday)
		*(*uintptr)(unsafe.Add(p, 1264)) = __ccgo_fp(_FHebmon)
		*(*uintptr)(unsafe.Add(p, 1296)) = __ccgo_fp(_FHebyear)
		*(*uintptr)(unsafe.Add(p, 1328)) = __ccgo_fp(_FHex)
		*(*uintptr)(unsafe.Add(p, 1360)) = __ccgo_fp(_FHour)
		*(*uintptr)(unsafe.Add(p, 1392)) = __ccgo_fp(_FHtmlEscape)
		*(*uintptr)(unsafe.Add(p, 1424)) = __ccgo_fp(_FHtmlStriptags)
		*(*uintptr)(unsafe.Add(p, 1464)) = __ccgo_fp(_FIif)
		*(*uintptr)(unsafe.Add(p, 1488)) = __ccgo_fp(_FIndex)
		*(*uintptr)(unsafe.Add(p, 1528)) = __ccgo_fp(_FIsAny)
		*(*uintptr)(unsafe.Add(p, 1560)) = __ccgo_fp(_FIsconst)
		*(*uintptr)(unsafe.Add(p, 1584)) = __ccgo_fp(_FIsdst)
		*(*uintptr)(unsafe.Add(p, 1616)) = __ccgo_fp(_FIsleap)
		*(*uintptr)(unsafe.Add(p, 1648)) = __ccgo_fp(_FIsomitted)
		*(*uintptr)(unsafe.Add(p, 1680)) = __ccgo_fp(_FIvritmon)
		*(*uintptr)(unsafe.Add(p, 1712)) = __ccgo_fp(_FJoin)
		*(*uintptr)(unsafe.Add(p, 1744)) = __ccgo_fp(_FLanguage)
		*(*uintptr)(unsafe.Add(p, 1776)) = __ccgo_fp(_FLocalToUTC)
		*(*uintptr)(unsafe.Add(p, 1808)) = __ccgo_fp(_FLower)
		*(*uintptr)(unsafe.Add(p, 1840)) = __ccgo_fp(_FMax)
		*(*uintptr)(unsafe.Add(p, 1872)) = __ccgo_fp(_FMbchar)
		*(*uintptr)(unsafe.Add(p, 1904)) = __ccgo_fp(_FMbindex)
		*(*uintptr)(unsafe.Add(p, 1936)) = __ccgo_fp(_FMblower)
		*(*uintptr)(unsafe.Add(p, 1968)) = __ccgo_fp(_FMbpad)
		*(*uintptr)(unsafe.Add(p, 2000)) = __ccgo_fp(_FMbstrlen)
		*(*uintptr)(unsafe.Add(p, 2032)) = __ccgo_fp(_FMbsubstr)
		*(*uintptr)(unsafe.Add(p, 2064)) = __ccgo_fp(_FMbupper)
		*(*uintptr)(unsafe.Add(p, 2096)) = __ccgo_fp(_FMin)
		*(*uintptr)(unsafe.Add(p, 2128)) = __ccgo_fp(_FMinsfromutc)
		*(*uintptr)(unsafe.Add(p, 2160)) = __ccgo_fp(_FMinute)
		*(*uintptr)(unsafe.Add(p, 2192)) = __ccgo_fp(_FMon)
		*(*uintptr)(unsafe.Add(p, 2224)) = __ccgo_fp(_FMonnum)
		*(*uintptr)(unsafe.Add(p, 2256)) = __ccgo_fp(_FMoondate)
		*(*uintptr)(unsafe.Add(p, 2288)) = __ccgo_fp(_FMoondatetime)
		*(*uintptr)(unsafe.Add(p, 2320)) = __ccgo_fp(_FMoonphase)
		*(*uintptr)(unsafe.Add(p, 2352)) = __ccgo_fp(_FMoonrise)
		*(*uintptr)(unsafe.Add(p, 2384)) = __ccgo_fp(_FMoonrisedir)
		*(*uintptr)(unsafe.Add(p, 2416)) = __ccgo_fp(_FMoonset)
		*(*uintptr)(unsafe.Add(p, 2448)) = __ccgo_fp(_FMoonsetdir)
		*(*uintptr)(unsafe.Add(p, 2480)) = __ccgo_fp(_FMoontime)
		*(*uintptr)(unsafe.Add(p, 2512)) = __ccgo_fp(_FMultiTrig)
		*(*uintptr)(unsafe.Add(p, 2544)) = __ccgo_fp(_FNDawn)
		*(*uintptr)(unsafe.Add(p, 2576)) = __ccgo_fp(_FNDusk)
		*(*uintptr)(unsafe.Add(p, 2608)) = __ccgo_fp(_FNonconst)
		*(*uintptr)(unsafe.Add(p, 2640)) = __ccgo_fp(_FNonomitted)
		*(*uintptr)(unsafe.Add(p, 2672)) = __ccgo_fp(_FNow)
		*(*uintptr)(unsafe.Add(p, 2704)) = __ccgo_fp(_FOrd)
		*(*uintptr)(unsafe.Add(p, 2736)) = __ccgo_fp(_FOrthodoxeaster)
		*(*uintptr)(unsafe.Add(p, 2768)) = __ccgo_fp(_FOstype)
		*(*uintptr)(unsafe.Add(p, 2800)) = __ccgo_fp(_FPad)
		*(*uintptr)(unsafe.Add(p, 2832)) = __ccgo_fp(_FPlural)
		*(*uintptr)(unsafe.Add(p, 2864)) = __ccgo_fp(_FPsmoon)
		*(*uintptr)(unsafe.Add(p, 2896)) = __ccgo_fp(_FPsshade)
		*(*uintptr)(unsafe.Add(p, 2928)) = __ccgo_fp(_FRealCurrent)
		*(*uintptr)(unsafe.Add(p, 2960)) = __ccgo_fp(_FRealnow)
		*(*uintptr)(unsafe.Add(p, 2992)) = __ccgo_fp(_FRealtoday)
		*(*uintptr)(unsafe.Add(p, 3024)) = __ccgo_fp(_FRows)
		*(*uintptr)(unsafe.Add(p, 3056)) = __ccgo_fp(_FSgn)
		*(*uintptr)(unsafe.Add(p, 3088)) = __ccgo_fp(_FShell)
		*(*uintptr)(unsafe.Add(p, 3120)) = __ccgo_fp(_FShellescape)
		*(*uintptr)(unsafe.Add(p, 3152)) = __ccgo_fp(_FSlide)
		*(*uintptr)(unsafe.Add(p, 3184)) = __ccgo_fp(_FSoleq)
		*(*uintptr)(unsafe.Add(p, 3216)) = __ccgo_fp(_FStdout)
		*(*uintptr)(unsafe.Add(p, 3248)) = __ccgo_fp(_FStrlen)
		*(*uintptr)(unsafe.Add(p, 3280)) = __ccgo_fp(_FSubstr)
		*(*uintptr)(unsafe.Add(p, 3312)) = __ccgo_fp(_FSunrise)
		*(*uintptr)(unsafe.Add(p, 3344)) = __ccgo_fp(_FSunset)
		*(*uintptr)(unsafe.Add(p, 3376)) = __ccgo_fp(_FTime)
		*(*uintptr)(unsafe.Add(p, 3408)) = __ccgo_fp(_FTimepart)
		*(*uintptr)(unsafe.Add(p, 3440)) = __ccgo_fp(_FTimezone)
		*(*uintptr)(unsafe.Add(p, 3472)) = __ccgo_fp(_FToday)
		*(*uintptr)(unsafe.Add(p, 3504)) = __ccgo_fp(_FTrig)
		*(*uintptr)(unsafe.Add(p, 3536)) = __ccgo_fp(_FTrigback)
		*(*uintptr)(unsafe.Add(p, 3568)) = __ccgo_fp(_FTrigbase)
		*(*uintptr)(unsafe.Add(p, 3600)) = __ccgo_fp(_FTrigcompletethrough)
		*(*uintptr)(unsafe.Add(p, 3632)) = __ccgo_fp(_FTrigdate)
		*(*uintptr)(unsafe.Add(p, 3664)) = __ccgo_fp(_FTrigdatetime)
		*(*uintptr)(unsafe.Add(p, 3696)) = __ccgo_fp(_FTrigdelta)
		*(*uintptr)(unsafe.Add(p, 3728)) = __ccgo_fp(_FTrigduration)
		*(*uintptr)(unsafe.Add(p, 3760)) = __ccgo_fp(_FTrigeventduration)
		*(*uintptr)(unsafe.Add(p, 3792)) = __ccgo_fp(_FTrigeventstart)
		*(*uintptr)(unsafe.Add(p, 3824)) = __ccgo_fp(_FTrigeventstarttz)
		*(*uintptr)(unsafe.Add(p, 3856)) = __ccgo_fp(_FTrigfrom)
		*(*uintptr)(unsafe.Add(p, 3888)) = __ccgo_fp(_FTrigger)
		*(*uintptr)(unsafe.Add(p, 3920)) = __ccgo_fp(_FTriginfo)
		*(*uintptr)(unsafe.Add(p, 3952)) = __ccgo_fp(_FTrigistodo)
		*(*uintptr)(unsafe.Add(p, 3984)) = __ccgo_fp(_FTrigmaxoverdue)
		*(*uintptr)(unsafe.Add(p, 4016)) = __ccgo_fp(_FTrigpriority)
		*(*uintptr)(unsafe.Add(p, 4048)) = __ccgo_fp(_FTrigrep)
		*(*uintptr)(unsafe.Add(p, 4080)) = __ccgo_fp(_FTrigscanfrom)
		*(*uintptr)(unsafe.Add(p, 4112)) = __ccgo_fp(_FTrigtags)
		*(*uintptr)(unsafe.Add(p, 4144)) = __ccgo_fp(_FTrigtime)
		*(*uintptr)(unsafe.Add(p, 4176)) = __ccgo_fp(_FTrigtimedelta)
		*(*uintptr)(unsafe.Add(p, 4208)) = __ccgo_fp(_FTrigtimerep)
		*(*uintptr)(unsafe.Add(p, 4240)) = __ccgo_fp(_FTrigtimetz)
		*(*uintptr)(unsafe.Add(p, 4272)) = __ccgo_fp(_FTrigtz)
		*(*uintptr)(unsafe.Add(p, 4304)) = __ccgo_fp(_FTriguntil)
		*(*uintptr)(unsafe.Add(p, 4336)) = __ccgo_fp(_FTrigvalid)
		*(*uintptr)(unsafe.Add(p, 4368)) = __ccgo_fp(_FTypeof)
		*(*uintptr)(unsafe.Add(p, 4400)) = __ccgo_fp(_FTzconvert)
		*(*uintptr)(unsafe.Add(p, 4432)) = __ccgo_fp(_FUpper)
		*(*uintptr)(unsafe.Add(p, 4464)) = __ccgo_fp(_FUTCToLocal)
		*(*uintptr)(unsafe.Add(p, 4504)) = __ccgo_fp(_FValue)
		*(*uintptr)(unsafe.Add(p, 4528)) = __ccgo_fp(_FVersion)
		*(*uintptr)(unsafe.Add(p, 4560)) = __ccgo_fp(_FWeekno)
		*(*uintptr)(unsafe.Add(p, 4592)) = __ccgo_fp(_FWkday)
		*(*uintptr)(unsafe.Add(p, 4624)) = __ccgo_fp(_FWkdaynum)
		*(*uintptr)(unsafe.Add(p, 4656)) = __ccgo_fp(_FYear)
	}
	{
		p := unsafe.Pointer(&_SysVarArr)
		*(*uintptr)(unsafe.Add(p, 368)) = __ccgo_fp(_date_sep_func)
		*(*uintptr)(unsafe.Add(p, 400)) = __ccgo_fp(_datetime_sep_func)
		*(*uintptr)(unsafe.Add(p, 496)) = __ccgo_fp(_default_color_func)
		*(*uintptr)(unsafe.Add(p, 528)) = __ccgo_fp(_default_color_func)
		*(*uintptr)(unsafe.Add(p, 848)) = __ccgo_fp(_expr_time_limit_func)
		*(*uintptr)(unsafe.Add(p, 1488)) = __ccgo_fp(_latdeg_func)
		*(*uintptr)(unsafe.Add(p, 1520)) = __ccgo_fp(_latitude_func)
		*(*uintptr)(unsafe.Add(p, 1552)) = __ccgo_fp(_latmin_func)
		*(*uintptr)(unsafe.Add(p, 1584)) = __ccgo_fp(_latsec_func)
		*(*uintptr)(unsafe.Add(p, 1648)) = __ccgo_fp(_longdeg_func)
		*(*uintptr)(unsafe.Add(p, 1680)) = __ccgo_fp(_longitude_func)
		*(*uintptr)(unsafe.Add(p, 1712)) = __ccgo_fp(_longmin_func)
		*(*uintptr)(unsafe.Add(p, 1744)) = __ccgo_fp(_longsec_func)
		*(*uintptr)(unsafe.Add(p, 2512)) = __ccgo_fp(_oncefile_func)
		*(*uintptr)(unsafe.Add(p, 3120)) = __ccgo_fp(_trig_date_func)
		*(*uintptr)(unsafe.Add(p, 3152)) = __ccgo_fp(_trig_base_func)
		*(*uintptr)(unsafe.Add(p, 3184)) = __ccgo_fp(_trig_day_func)
		*(*uintptr)(unsafe.Add(p, 3216)) = __ccgo_fp(_terminal_bg_func)
		*(*uintptr)(unsafe.Add(p, 3312)) = __ccgo_fp(_time_sep_func)
		*(*uintptr)(unsafe.Add(p, 3344)) = __ccgo_fp(_timet_is_64_func)
		*(*uintptr)(unsafe.Add(p, 3376)) = __ccgo_fp(_trig_mon_func)
		*(*uintptr)(unsafe.Add(p, 3504)) = __ccgo_fp(_trig_time_func)
		*(*uintptr)(unsafe.Add(p, 3536)) = __ccgo_fp(_trig_until_func)
		*(*uintptr)(unsafe.Add(p, 3600)) = __ccgo_fp(_trig_wday_func)
		*(*uintptr)(unsafe.Add(p, 3632)) = __ccgo_fp(_trig_year_func)
		*(*uintptr)(unsafe.Add(p, 3664)) = __ccgo_fp(_today_date_func)
		*(*uintptr)(unsafe.Add(p, 3696)) = __ccgo_fp(_today_day_func)
		*(*uintptr)(unsafe.Add(p, 3728)) = __ccgo_fp(_today_mon_func)
		*(*uintptr)(unsafe.Add(p, 3920)) = __ccgo_fp(_today_wday_func)
		*(*uintptr)(unsafe.Add(p, 3952)) = __ccgo_fp(_today_year_func)
		*(*uintptr)(unsafe.Add(p, 3984)) = __ccgo_fp(_warning_level_func)
	}
}
